
//format of the list
//examname
//subject
//int questionNumber
//question
//year
//bool: isquestionimage
//string: questionimage
//string: option1
//string: option2
//string: option3
//string: option4
//bool: isoptionimage
//imagelink: option1
//imagelink: option2
//imagelink: option3
//imagelink: option4
//string or bool: answer
//string + image: explanation
//bool: isexplanationimage
//String: image

List<List<dynamic>> jee_mains_2024_set_1 = [
  [
    "jeemain",
    "maths",
    1,
    "The total number of three-digit numbers, divisible by 3, which can be formed using the digits 1, 3, 5, 8, if repetition of digits is allowed, is:",
    2023,
    false,
    "",
    "22",
    "18",
    "21",
    "20",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "22 three-digit numbers can be formed using the digits 1, 3, 5, and 8 (with repetition allowed) that are divisible by 3",
    "",
  ],
  [
    "jeemain",
    "maths",
    2,
    "Let S be the set of all values of λ, for which the shortest distance between x +λ ---32+6 and += 0 4 1 Then 8 ∑ is equal to 3 the z-6 0 lines is 13. y -4",
    2023,
    false,
    "",
    "304",
    "308",
    "306",
    "302",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "make it little short Find Slopes:Line 1: y = (-1/λ)x + 26/λLine 2: y = -4x + 42. Use Distance Formula:13 = |(26/λ - 4) / √(1 + 1/λ^2) * √(1 + 16)|3. Solve for λ:Simplify and solve the resulting quadratic equation.4. Sum of λ Values:Add the two values of λ obtained.",
    "",
  ],
  [
    "jeemain",
    "maths",
    3,
    "The mean and standard deviation of 10 observations are 20 and 8 respectively. Later on, it was observed that one observation was recorded as 50 instead of 40. Then the correct variance is:",
    2023,
    false,
    "",
    "14",
    "13",
    "12",
    "11",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "1. Correct Data:Adjust sum: 200 - 50 + 40 = 190Adjust sum of squares: 4640 - 50^2 + 40^2 = 37402. New Mean:190 / 10 = 19. New Variance:(3740 - 19^2 * 10) / 9 ≈ 14Answer: The correct variance is approximately 14.44.",
    "",
  ],
  [
    "jeemain",
    "maths",
    4,
    "Let ABCD be a quadrilateral. If E and F are the mid points of the diagonals AC and BDrespectively and (AB- BC)+(AD-DC)=k FE.then k is equal to",
    2023,
    false,
    "",
    "2",
    "-2",
    "-4",
    "4",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Consider Triangles:triangle ABC, EF is parallel to BC and EF = 1/2 BC.Intriangle ADC, EF is parallel to DC and EF = 1/2 DC.Express AB - BC and AD - DC in terms of EF:AB - BC = 2EF (from triangle ABC)AD - DC = 2EF (from triangle ADC)Substitute and Solve:(AB - BC) + (AD - DC) = 2EF + 2EF = 4EFTherefore, k = 4",
    "",
  ],
  [
    "jeemain",
    "maths",
    5,
    "Let x =x(y) be the solution of the differential equat2(y+2)log.(y+2)dx+（x+4-2loge(y+2))dy=(y>-1 withx (e -2)=1.Thenx (e -2) is equal to",
    2023,
    false,
    "",
    "49",
    "103",
    "32",
    "39",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Rearrange:Rewrite the equation as: dx/dy = -(x + 4 - 2log(y + 2)) / (2(y + 2)*log(y + 2))2. Solve:This is a first-order linear differential equation.Find the integrating factor and solve for x(y).3. Evaluate:Use the initial condition x(e - 2) = 1 to find the constant of integration.Substitute y = e - 2 to find x(e - 2).",
    "",
  ],
  [
    "jeemain",
    "maths",
    6,
    "Let [x] denote the greatest integer function and f(x) = max {1 + x + [x], 2 + x, x + 2[x]}, 0 ≤ x ≤ 2. Let m be the number of points in [0,2], where f is not continuous and n be the number of points in (0,2), where f is not differentiable. Then (m+n)² + 2 is equal to:",
    2023,
    false,
    "",
    "11",
    "2",
    "6",
    "3",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "1. Analyze:Find critical points where the 'max' function changes.Evaluate f(x) in intervals where [x] changes.2. Find:Discontinuities: Points where left and right limits of f(x) differ.Non-differentiability: Points where the derivative of f(x) doesn't exist.3. Calculate:Count discontinuities (m) and non-differentiability points (n).Calculate (m + n)² + 2.",
    "",
  ],
  [
    "jeemain",
    "maths",
    7,
    "The number of real roots of the equation xx-5x+2+6=0, is",
    2023,
    false,
    "",
    "5",
    "3",
    "6",
    "4",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Analyze:Consider cases for x: x ≥ 0, -2 ≤ x < 0, x < -2.Simplify the equation using |x| and |x + 2| definitions for each case.2. Solve:Solve the resulting quadratic equations in each case.3. Check & Count:Verify if the roots satisfy the conditions of their respective cases.Count the number of valid real roots.",
    "",
  ],
  [
    "jeemain",
    "maths",
    8,
    "Let (a + bx +cx2)10 20 = Σρχ', x¹, a, b, c ∈ N. If p₁ = 20 1 i=0 and p2 = 210, then 2(a + b + c) is equal to",
    2023,
    false,
    "",
    "8",
    "12",
    "15",
    "6",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    " Understand the Equation:The given equation involves the expansion of (a + bx + cx²)¹⁰ using the binomial theorem.The expansion will result in a polynomial of degree 20.p₁, p₂, ..., p₂₀ are the coefficients of the terms in this polynomial.2. Use Given Information:p₁ = 20: This likely relates to the coefficient of the x¹ term in the expansion.p₂ = 210: This likely relates to the coefficient of the x² term in the expansion.3. Determine Relationships:You'll need to use the binomial theorem and the given values of p₁ and p₂ to establish relationships between a, b, and c.4. Solve for a, b, and c:Solve the derived equations to find the values of a, b, and c.5. Calculate 2(a + b + c):Once you have the values of a, b, and c, calculate 2(a + b + c).",
    "",
  ],
  [
    "jeemain",
    "maths",
    9,
    "Let the determinant of a square matrix A of order m bemn, where m and n satisfy 4m + n = 22 and 17m + 4n 93. If det (n adj (adj (mA))) = 3ª56. then a + b + c is equal to:",
    2023,
    false,
    "",
    "96",
    "101",
    "109",
    "84",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    " Solve: Find m and n using the given equations.2. Det(A): Calculate det(A) = mn.3. Adjoint: Use det(adj(adj(mA))) = (det(mA))^(m-1)²4. Equate: Set det(n adj(adj(mA))) = 3ª56 and solve for a, b, c.5. Calculate: Find a + b + c.",
    "",
  ],
  [
    "jeemain",
    "maths",
    10,
    "Let A₁ and A₂ be two arithmetic means and G1, G2, G3 be three geometric means of two distinct positive numbers. The G+G+G+GiGis equal to",
    2023,
    false,
    "",
    "2(A1 + A2)G1G3",
    "(2) (A1+A2) GG3",
    "(A1+A2)GG",
    "2(A+A₂)GG",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Key: A₁ = A₂, G₁ = G₂ = G₃, Arithmetic Mean (A) ≥ Geometric Mean (G)Simplify: (G₁ + G₂ + G₃) * G₁ * G₃ = 3 * (√(a * b))³Compare: 2 * (A₁ + A₂) ≥ 4 * √(a * b) > 3 * (√(a * b))³Conclusion: None of the given options are correct.",
    "",
  ],
  [
    "jeemain",
    "maths",
    11,
    "If the set Re Z-Z+ZZ 2-3z+5Z :ze C, Re(z)=3 is equal to the interval (α.β], then 24 (ẞa) is equal to",
    2023,
    false,
    "",
    "36",
    "42",
    "27",
    "30",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Simplify the Expression:Substitute z = 3 + iy (where y is any real number) into the given expression.Simplify the expression to find the real part2. Determine the Range:Find the minimum and maximum values of the simplified real part.This will give you the interval (α, β].3. Calculate 24(β - α):Subtract α from β.Multiply the result by 24.",
    "",
  ],
  [
    "jeemain",
    "maths",
    12,
    " The number of common tangents, to the circles  x² + y²-18x-15y + 131 = 0 and x²+y²-6x-6y-7=0, is:",
    2023,
    false,
    "",
    "3",
    "2",
    "1",
    "4",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Find Centers and Radii: Determine the centers and radii of the two circles from their equations.2. Distance Between Centers: Calculate the distance between the centers of the circles.3. Compare Distances and Radii:If |r1 - r2| < distance < r1 + r2, the circles intersect, and there are 2 common tangents.",
    "",
  ],
  [
    "jeemain",
    "maths",
    13,
    "Negation of p^(q^~(p^q)) is",
    2023,
    false,
    "",
    "~(pvq)",
    "pvq",
    "((bvd)~) (ε)",
    "(~(p^q)) vp",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Apply De Morgan's Law:De Morgan's Law states: ~(p ∧ q) = ~p ∨ ~qApply this to the inner part of the expression: ~(p ∧ q) = ~p ∨ ~q2. Simplify:The expression becomes: p ∧ (q ∧ (~p ∨ ~q))Since (~p ∨ ~q) is always true (tautology), the entire expression simplifies to: 3. Negate the Simplified Expression:The negation of p is ~p",
    "",
  ],
  [
    "jeemain",
    "maths",
    14,
    "Let the system of linear equations -x+2y-9z-7-x+3y+7z9-2x+y+5z8 -3x + y + 13z = λ  has a unique solution x = a, y = ẞ, z = y. Then the distance of the point (α, β,γ) from the plane 2x - 2y + z = A is",
    2023,
    false,
    "",
    "9",
    "11",
    "13",
    "7",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    " Solve the System: Find the unique solution (α, β, γ) for the given system of linear equations.2. Use Distance Formula:The distance from point (α, β, γ) to plane 2x - 2y + z = A is: |2α - 2β + γ - A| / √(2² + (-2)² + 1²) This formula calculates the perpendicular distance between the point and the plane.",
    "",
  ],
  [
    "jeemain",
    "maths",
    15,
    "If (α, β) is the orthocentre of the triangle ABC with vertices A(3, -7), B(-1, 2) and C(4, 5), then 9a-6ẞ + 60 is equal to:",
    2023,
    false,
    "",
    "30",
    "25",
    "40",
    "35",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "If (α, β) is the orthocentre of the triangle ABC with vertices A(3, -7), B(-1, 2) and C(4, 5), then 9a-6ẞ + 60 is equal to:",
    "",
  ],
  [
    "jeemain",
    "maths",
    16,
    " Let the foot of perpendicular of the point P(3, -2,-9) on the plane passing through the points (-1, -2, -3), (9, 3, 4), (9, -2, 1) be Q (α, β, γ). Then the distance of Q from the origin is:",
    2023,
    false,
    "",
    "√29",
    "√35",
    "√42",
    "√38",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Find Plane Equation: Determine the equation of the plane passing through the given points.2. Find Line PQ: Determine the equation of the line perpendicular to the plane and passing through point P(3, -2, -9).3. Find Point Q: Find the intersection point of the line PQ and the plane. This is the foot of the perpendicular, Q(α, β, γ).4. Calculate Distance: Calculate the distance between point Q and the origin using the distance formula: √(α² + β² + γ²).",
    "",
  ],
  [
    "jeemain",
    "maths",
    17,
    "A bag contains 6 white and 4 balls. A die is rolled once and the number of balls equal to the number obtained on the die are drawn from the bag at random. The probability that all the balls drawn are white is:",
    2023,
    false,
    "",
    "1/4",
    "9/50",
    "1/5",
    "11/50",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Determine Possible Outcomes:A die has 6 faces, so the possible number of balls drawn can be 1, 2, 3, 4, 5, or 6.2. Calculate Probabilities:For each possible number of balls drawn:Calculate the probability of drawing that number on the die (1/6).Calculate the probability of drawing that many white balls from the bag.3. Sum Probabilities:Sum the probabilities calculated in step 2 for all possible numbers of balls drawn.",
    "",
  ],
  [
    "jeemain",
    "maths",
    18,
    " If So 1 (5+2x-2x²)(1+e(2-4x)) 4 1 dx = -loge α α, β> > 0, then aẞ is equal to: α +1 β",
    2023,
    false,
    "",
    "21",
    "0",
    "19",
    "-21",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Evaluate Integral: Calculate the integral ∫₀¹ (5 + 2x - 2x²)(1 + e^(2-4x)) dx.2. Solve for α: Use the integral's value to find α from the equation I = -logₑ(α).3. Determine β: Solve for β using α + 1/β = 4.4. Calculate αβ: Multiply α and β to find the value of αβ.",
    "",
  ],
  [
    "jeemain",
    "maths",
    19,
    "Let S be the set of all (λ, μ) for which the vectors ai-j+ki+2j+µk and 3i-4j+5k, where λ – μ = 5, are coplanar, then Σ 80(λ² +μ²) is (λ.μ)ες equal to:",
    2023,
    false,
    "",
    "2370",
    "2130",
    "2290",
    "2210",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Coplanarity Condition:Vectors are coplanar if their scalar triple product is zero.2. Find Possible Solutions:Set up the scalar triple product equation.Use the constraint λ - μ = 5.Solve the system of equations to find possible values for λ and μ.3. Calculate and Sum:For each valid (λ, μ) pair, calculate 80(λ² + μ²).Sum these values to get the final answer.",
    "",
  ],
  [
    "jeemain",
    "maths",
    20,
    "If the domain of the function f(x) = loge (4x²+11x+6) + sin-¹ (4x + 3) + cos^* (10x+6) is (α, β], -1 Then 36 a + β is equal to:",
    2023,
    false,
    "",
    "63",
    "45",
    "72",
    "54",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Find Domain: Determine the domain for each term (log, sin⁻¹, cos⁻¹) based on their argument restrictions.2. Find Overlapping Domain:Find the common domain for all terms.3. Identify α and β:Determine the values of α and β from the overlapping domain.4. Calculate 36α + β:Substitute the values of α and β and calculate the result.Answer: 36α + β = -55/2",
    "",
  ],
  [
    "jeemain",
    "maths",
    21,
    "If the sum of the series 11 2 3 + 22 + 2.3 2 + 1 1 1 1 + 23 22.3 2.32 33 1 1 1 + + 23330)+is where 1 1 24 23.3 22.32 2.33 34 α β a and ẞ are co-prime, then a + 3ẞ is equal to...",
    2023,
    false,
    "",
    "32",
    "44",
    "52",
    "14",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Identify the Series: The series is 1 + (1+2)/2 + (1+2+3)/3 + ...2. Find General Term:The nth term is (n+1)/2.3. Determine Convergence:Analyze the series' convergence (if it converges to a finite sum).4. Find Sum (if convergent):Determine the sum of the series.5. Find α and β:If the sum is S, then S = α/β (where α and β are co-prime).6. Calculate α + 3β:Calculate α + 3β using the found values of α and β.",
    "",
  ],
  [
    "jeemain",
    "maths",
    22,
    "A person forgets his 4-digit ATM pin code. But he remembers that in the code all the digits are different, the greatest digit is 7 and the sum of the first two digits is equal to the sum of the last two digits. Then the maximum number of trials necessary to obtain the correct code is",
    2023,
    false,
    "",
    "22",
    "34",
    "54",
    "60",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Find Possible Codes:Determine all 4-digit codes that satisfy the given conditions (distinct digits, greatest digit is 7, sum of first two digits equals sum of last two digits).2. Count Codes:Count the total number of possible codes.3. Maximum Trials:The maximum number of trials is equal to the number of possible codes.",
    "",
  ],
  [
    "jeemain",
    "maths",
    23,
    "Let the plane P contain the line 2x+y-z-305x3y+4z+9 and be parallel to the line x+23-yz-7 = = 2 -4 5 Then the distance of the point A(8, -1, -19) from the plane I to the line P measured parallel to the line is equal to X -3 Y-5-2-2 4 -12",
    2023,
    false,
    "",
    "56",
    "77",
    "83",
    "93",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "1. Find Plane Equation: Determine the equation of the plane P. 2. Find Distance to Plane: Calculate the distance from point A to plane P.3. Project Distance: Project the distance found in step 2 onto the direction vector of the parallel line.",
    "",
  ],
  [
    "jeemain",
    "maths",
    24,
    "Let an ellipse with centre (1, 0) and latus rectum of length 1 1 2 have its major axis along x-axis. If its minor axis subtends an angle 60° at the foci, then the square of the sum of the lengths of its minor and major axes is equal to",
    2023,
    false,
    "",
    "85",
    "76",
    "98",
    "100",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "1. Key Info: Center: (1, 0) Major Axis: Along x-axis Latus Rectum: 1/2 Minor Axis Angle at Foci: 60° 2. Find 'a' and 'b': Use relationships between 'a', 'b', and eccentricity (derived from given info). 3. Calculate Sum of Axes: Calculate 2a + 2b. 4. Square the Sum: Square the result from step 3.",
    "",
  ],
  [
    "jeemain",
    "maths",
    25,
    "Let A = {1,2,3,4} and R be a relation 0n the set A × A defined by R=((ab）.(cd)):2a+3b=4c+5dy. Then the number of elements in R is:",
    2023,
    false,
    "",
    "90",
    "81",
    "94",
    "105",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Define Relation: R = {((a, b), (c, d)) | 2a + 3b = 4c + 5d} on A x A, where A = {1, 2, 3, 4} 2. Find Elements: Determine ordered pairs ((a, b), (c, d)) satisfying the relation. 3. Count Elements: Count the number of ordered pairs that satisfy the relation.",
    "",
  ],
  [
    "jeemain",
    "maths",
    26,
    "The number of elements in the set (ne N:10sn <100 and 3 -3 is a multiple o is",
    2023,
    false,
    "",
    "18",
    "20",
    "22",
    "30",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Condition: Find 'n' (10 ≤ n < 100) where 3^n - 3 is a multiple of 8 (i.e., 3^n ≡ 3 (mod 8)) 2. Find Pattern: Determine the pattern of 3^n modulo 8. 3. Count Elements:Count the 'n' values within the range that satisfy the condition.",
    "",
  ],
  [
    "jeemain",
    "maths",
    27,
    "If the line x =y = z intersects the line x sin A + y sin B + z sin C - 18 =0 =x sin 2A + y sin 2B + z sin 2C -9, where A, B, C are the angles of a A B C is equal triangle ABC, then 80 sin — sin —sin 2 2 2 to",
    2023,
    false,
    "",
    "22",
    "30",
    "34",
    "40",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Find Intersection: Determine the point of intersection of the line x = y = z with the given planes. 2. Use Trigonometric Relations: Substitute the intersection point into the plane equations. Use trigonometric identities (e.g., sin 2A = 2sin A cos A) and properties of triangles (e.g., sum of angles in a triangle). 3. Solve for sin(A/2)sin(B/2)sin(C/2): Manipulate the equations to isolate sin(A/2)sin(B/2)sin(C/2). 4. Calculate 80 sin(A/2)sin(B/2)sin(C/2): Substitute the found value of sin(A/2)sin(B/2)sin(C/2) into the expression.",
    "",
  ],
  [
    "jeemain",
    "maths",
    28,
    "If the area bounded by the curve zy*=3x,ln x+y=3,y =0 and outside the circle (x-3)*+y= is A, then 4 (T + 4A) is equal to",
    2023,
    false,
    "",
    "55",
    "47",
    "89",
    "90",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Find Intersections: Determine the points where the curves intersect. 2. Calculate Areas: Find the area under the curves. Find the area of the circle. 3. Calculate A: Subtract the circle's area from the total area under the curves. 4. Evaluate 4(π + 4A): Substitute the value of A and calculate.",
    "",
  ],
  [
    "jeemain",
    "maths",
    29,
    "Consider the triangles with vertices A(2, 1) B (0, 0) and C (t, 4),t e [0,4]. It the maximum and the minimum perimeters of such triangles are obtained at t =α and t =β respectively, then 6α + 21β is equal to",
    2023,
    false,
    "",
    "12",
    "21",
    "11",
    "14",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "1. Find Perimeter: Express the triangle's perimeter as a function of 't'. 2. Find Critical Points: Differentiate the perimeter function and find critical points. 3. Determine α and β: Find the values of 't' (α and β) that give the maximum and minimum perimeters, considering the interval [0, 4]. 4. Calculate 6α + 21β: Substitute the values of α and β into the expression.",
    "",
  ],
  [
    "jeemain",
    "maths",
    30,
    "Let f(x)= dx 2 < J. If f(O) = （3+4x2）V4-3x? 1 tan ~1 and f(1) =- equal to",
    2023,
    false,
    "",
    "54",
    "56",
    "32",
    "28",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Evaluate Integral: Find the integral of the given function. Apply Conditions: Use the given conditions f(0) = 0 and f(1) = -(1/4) * arctan(2/√3) to verify the solution.",
    "",
  ],
  [
    "jeemain",
    "physics",
    31,
    "The electric field due to a short electric dipole at large distance (r) from center of dipole on th equatorial plane varies with distance as:",
    2023,
    false,
    "",
    "r",
    "l-r",
    "1F1",
    "r-1",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "The electric field due to a short electric dipole at a large distance (r) from the center of the dipole on the equatorial plane varies with distance as 1/r³.",
    "",
  ],
  [
    "jeemain",
    "physics",
    32,
    "In a linear simple harmonic motion(SHM) (A) Restoring force is directly proportional to t displacement. (B) The acceleration and displacement are opposite in direction. (C) The velocity is maximum at mean position. (D) The acceleration is minimum at extren points. Choose the correct answer from the options give below：",
    2023,
    false,
    "",
    "(A), (B) and (C) only",
    "(C) and (D) only",
    "(A), (B) and (D) only",
    "(A), (C) and (D) only",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Key SHM Characteristics: Restoring Force: Proportional to displacement, opposite direction. Velocity: Max at mean position, zero at extremes. Acceleration: Max at extremes, zero at mean position. Correct Answer: (4) (A), (C), and (D) only",
    "",
  ],
  [
    "jeemain",
    "physics",
    33,
    "Two identical particles each of mass‘m'go round a circle of radius a under the action of their mutual gravitational attraction.The angular speed of each particle will be: Gm Gm",
    2023,
    false,
    "",
    "2@",
    "8@",
    "9Gm",
    "10 Gm",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "Equate Forces: Gravitational force = Centripetal force Solve for ω: (Gmm)/(4a²) = mω²a ω = √(G*m)/(2a^(3/2)) ω: Angular speed of each particle",
    "",
  ],
  [
    "jeemain",
    "physics",
    34,
    "The height of transmitting antenna is 180 m and the height of the receiving antenna is 245 m.The maximum distance between them for satisfactory communication in line of sight will be: (given R =6400 km) ",
    2023,
    false,
    "",
    "48 km",
    "56 km",
    "96 km",
    "104km",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Formula: Maximum distance (d) = √(2RhT) + √(2RhR) R: Earth's radius hT, hR: Antenna heights Calculate: Substitute values, solve for 'd'. Result: Maximum distance ≈ 104 km",
    "",
  ],
  [
    "jeemain",
    "physics",
    35,
    "The half-life of a radioactive nucleus is 5 year The fraction of the original sample that Wou decay in 15 years is: ",
    2023,
    false,
    "",
    "1/8",
    "1/4",
    "7/8",
    "3/4",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "Half-life: In 5 years, half of the sample decays. 15 Years: 15 years is 3 half-lives (15 years / 5 years/half-life = 3). Fraction Remaining: After 3 half-lives: (1/2) * (1/2) * (1/2) = 1/8 Fraction Decayed: 1 - (1/8) = 7/8 Answer: (3) 7/8",
    "",
  ],
  [
    "jeemain",
    "physics",
    36,
    "The de Broglie wavelength of an electron having kinetic energy E is A. If the kinetic energy of electron becomes wavelength will be : E - 4' then its de-Broglie",
    2023,
    false,
    "",
    "λ/sqrt(2)",
    "λ/2",
    "2λ",
    "sqrt(2)*λ",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "de Broglie Wavelength: λ = h/p h: Planck's constant1  1Planck constant - Wikipedia en.wikipedia.org p: momentum (p = √(2mE)) New Kinetic Energy: E' = E/4 New Momentum: p' = √(2mE') = √(2m(E/4)) = (1/2)√(2mE) = p/2 New Wavelength: λ' = h/p' = h/(p/2) = 2λ Answer: (3) 2λ",
    "",
  ],
  [
    "jeemain",
    "physics",
    37,
    "For designing a voltmeter of range 50 V and an ammeter of range 10 mA using a galvanometer which has a coil of resistance 54 Ω showing a full scale deflection for 1 mA as in figure.",
    2023,
    false,
    "",
    "for voltmeter R ≈ 50 ΚΩ",
    "for ammeter r ≈ 0.2 Ω",
    "for ammeter r = 6 Ω",
    "for voltmeter R = 5 ΚΩ",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Voltmeter: High resistance (R) in series. V = Ig * (R + G) R ≈ 50 kΩ Ammeter: Low resistance shunt (r) in parallel. Ig * G = (I - Ig) * r ≈ 6 Ω",
    "",
  ],
  [
    "jeemain",
    "physics",
    38,
    "(A flask contains Hydrogen and Argon in the ratio 2:1 by mass. The temperature of the mixture is 30°C. The ratio of average kinetic energy per molecule of the two gases (K argon/K hydrogen) is: (Given: Atomic Weight of Ar = 39.9)",
    2023,
    false,
    "",
    "1",
    "2",
    "39.92",
    "39.9",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "The ratio of average kinetic energy per molecule of the two gases is 1. Here's why: Kinetic Energy and Temperature: In an ideal gas, the average kinetic energy of gas molecules is directly proportional to the absolute temperature.Same Temperature: Since both Hydrogen and Argon are in the same flask and at the same temperature, their average kinetic energies per molecule are equal.Therefore, the ratio of the average kinetic energy per molecule of Argon to that of Hydrogen is 1.",
    "",
  ],
  [
    "jeemain",
    "physics",
    39,
    "Given below are two statements: Statement I: The equivalent resistance of resistors in a series combination is smaller than least resistance used in the combination. Statement II: The resistivity of the material is independent of temperature. In the light of the above statements, choose the correct answer from the options given below: (1) Statement I is false but Statement II is true (2) Both Statement I and Statement II are false (3) Statement I is true but Statement II is false (4) Both Statement I and Statement II are true",
    2024,
    false,
    "",
    "Statement I is false but Statement II is true",
    "Both Statement I and Statement II are false",
    "Statement I is true but Statement II is false",
    "Both Statement I and Statement II are true",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Statement I (False): In a series combination, the equivalent resistance is always greater than the resistance of any individual resistor. Statement II (False): The resistivity of most materials does depend on temperature. For example, the resistivity of metals generally increases with increasing temperature. Therefore, the correct answer is (2) Both Statement I and Statement II are false.",
    "",
  ],
  [
    "jeemain",
    "physics",
    40,
    "A body is released from a height equal to the radius (R) of the earth. The velocity of the body when it strikes the surface of the earth will be: (Given g = acceleration due to gravity on the earth.)",
    2024,
    false,
    "",
    "√gR",
    "4gR",
    "√2gR",
    "gR 2",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Conservation of Energy: Initial Potential Energy (at height R) = Final Kinetic Energy -GMm/(2R) = (1/2)mv² Solve for v: v² = GM/R Since g = GM/R², we get v² = 2gR v = √(2gR) Answer: (3) √2gR",
    "",
  ],
  [
    "jeemain",
    "physics",
    41,
    "A 12 V battery connected to a coil of resistance 6 Ω through a switch, drives a constant current in the circuit. The switch is opened in 1 ms. The emf induced across the coil is 20 V. The inductance of the coil is:",
    2024,
    false,
    "",
    "5 mH",
    "12 mH",
    "8 mH",
    "10 mH",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Steady-State Current: I = V/R = 2 A Faraday's Law: ε = -L (dI/dt) Calculate Inductance: 20 V = -L * (-2000 A/s) L = 10 mH",
    "",
  ],
  [
    "jeemain",
    "physics",
    42,
    "A wire of length 'L' and radius 'r' is clamped rigidly at one end. When the other end of the wire is pulled by a force f, its length increases by 'l'. Another wire of same material of length '2L' and radius '2r' is pulled by a force '2f. Then the increase in its length will be :",
    2024,
    false,
    "",
    "2l",
    "l",
    "4l",
    "l/2",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Young's Modulus: Relates stress and strain (constant for the material). First Wire: Calculate elongation (l) using Young's Modulus.vSecond Wire: Calculate elongation (ΔL) using Young's Modulus. Compare Elongations: ΔL = l Answer: (1) l",
    "",
  ],
  [
    "jeemain",
    "physics",
    43,
    "The position of a particle related to time is given by x = (5t4t+5)m. The magnitude of velocity of the particle at t = 2s will be :",
    2024,
    false,
    "",
    "10 ms-¹",
    "14 ms-¹",
    "16 ms¹",
    "06 ms¹",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "1. Find Velocity: Velocity (v) is the derivative of position (x) with respect to time (t): v = dx/dt = d(5t² - 4t + 5)/dt = 10t - 4 2. Calculate Velocity at t = 2s: Substitute t = 2s into the velocity equation: v = 10(2) - 4 = 20 - 4 = 16 m/s Answer: (3) 16 ms⁻¹",
    "",
  ],
  [
    "jeemain",
    "physics",
    44,
    "The position vector of a particle related to time t is given by r = (10ti+15t²j+7k)m The direction of net force experienced by the particle is:",
    2024,
    false,
    "",
    "Positive y-axis",
    "Positive x-axis",
    "Positive z-axis",
    "In x-y plane",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Find Acceleration: a = dv/dt = 30j Direction of Force: Same as acceleration, positive y-axis. Answer: (1) Positive y-axis",
    "",
  ],
  [
    "jeemain",
    "physics",
    45,
    "Match List I with List II of Electromagnetic waves with corresponding wavelength range: List I List II (A) Microwave (I) 400 nm to 1 nm (B) Ultraviolet (II) 1 nm to 103 nm (C) X-Ray (III) 1 mn to 700 nm (D) Infra-red (IV) 0.1 m to 1mm Choose the correct answer from the options given below:",
    2024,
    false,
    "",
    "(A)-(I), (B)-(IV), (C)-(II), (D)-(III)",
    "(A)-(IV), (B)-(I), (C)-(II), (D)-(III)",
    "(A)-(IV), (B)-(II), (C)-(I), (D)-(III)",
    "(A)-(IV), (B)-(I), (C)-(III), (D)-(II)",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Angle with x-axis: 60° y-component: 2√3 x-component: Magnitude * cos(60°) Find Magnitude: Magnitude = 4√3 Calculate x-component: 4√3 * (1/2) = 2√3 Answer: (1) 2√3",
    "",
  ],
  [
    "jeemain",
    "physics",
    46,
    "The speed of a wave produced in water is given by u = λª gο ρε. Where 2, g and pare wavelength of wave, acceleration due to gravity and density of water respectively. The values of a, b and c respectively, are:",
    2024,
    false,
    "",
    "-,-,0 22",
    "1, 1, 0",
    "1,-1,0",
    "1, 0 , 22",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Dimensional Analysis: Equate dimensions of 'v' with the dimensions of the given equation. Solve Equations: Obtain equations for exponents of L, T, and M. Solve the system of equations. Find a, b, c: a = 1/2, b = 1/2, c = 0 Answer: (2) 1/2, 1/2, 0",
    "",
  ],
  [
    "jeemain",
    "physics",
    47,
    " A vector in x-y plane makes an angle of 30° with y-axis The magnitude of y-component of vector is 2√3. The magnitude of x-component of the vector will be:",
    2024,
    false,
    "",
    "1/√3 ",
    "6",
    "√3",
    "2",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Use dimensional analysis to equate dimensions in the given equation. Solve the resulting equations for exponents 'a', 'b', and 'c'. Find: a = 1/2, b = 1/2, c = 0 Answer: (2) 1/2, 1/2, 0",
    "",
  ],
  [
    "jeemain",
    "physics",
    48,
    "A single slit of width a is illuminated by a monochromatic light of wavelength 600 nm. The value of 'a' for which first minimum appears at 0=30° on the screen will be:",
    2024,
    false,
    "",
    "0.6 µm",
    "1.2 µm",
    "1.8 µm",
    "3 µm",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Single-Slit Diffraction: a * sin(θ) = λ Calculate Slit Width: a = λ / sin(θ) = 1.2 µm Answer: (2) 1.2 µm",
    "",
  ],
  [
    "jeemain",
    "physics",
    49,
    "A thermodynamic system is taken through cyclic process. The total work done in the process is: 400 DP (Pa) 100 C E 24←V(m³)",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736679439/Q49_jkcxdq.jpg",
    "100 J",
    "300 J",
    "Zero",
    "200 J",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Cyclic Process: The system returns to its initial state. Work in Cyclic Process: In a cyclic process, the net work done is equal to the area enclosed by the cycle on the P-V diagram. In this case: The area enclosed by the cycle appears to be a triangle. Calculate the area of the triangle to find the net work done.",
    "",
  ],
  [
    "jeemain",
    "physics",
    50,
    "In the given circuit, the current (I) through the battery will be:",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736682460/Q.50_wuzaoc.jpg",
    "1.5 A",
    "1 A",
    "2.5 A",
    "2 A",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Analyze Circuit: D2 (reverse-biased) is open. D1, D3 (forward-biased) are short circuits. Calculate Resistance: Equivalent resistance: R_total = 10 Ω + (1/10 + 1/10 + 1/10)^-1 = 40/3 Ω Find Current: I = V / R_total = 10 V / (40/3 Ω) = 0.75 A Answer: 0.75 A",
    "",
  ],
  [
    "jeemain",
    "physics",
    51,
    "A 20 cm long metallic rod is rotated with 210 rpm about an axis normal to the rod passing through its one end. The order end of the rod is in contact with a circular metallic ring. A constant and uniform magnetic field 0.2T parallel to the axis exists everywhere. The emf developed between the centre and the ring is mV. Take π = 22 7",
    2024,
    false,
    "",
    "0.150",
    "0.120",
    "0.110",
    "0.176",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Find Angular Velocity: ω = 2π * (rpm) / 60 Find Linear Velocity: v = ω * r Calculate EMF: EMF = B * l * Answer: 0.176 mV",
    "",
  ],
  [
    "jeemain",
    "physics",
    52,
    "A network of four resistances is connected to 9V battery, as shown in figure. The magnitude of voltage difference between the points A and B is ___V.",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736683299/Q.52_ckdas5.jpg",
    "4 Ω",
    "20 Ω",
    "24 Ω",
    "30 Ω",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Simplify: Two 4Ω resistors in parallel become 2Ω. Total Resistance: R_total = 2Ω + 2Ω = 4Ω Current: I = V / R_total = 9V / 4Ω = 2.25 A Voltage Across AB: 2.25 A * 2Ω = 4.5 V Answer: 4.5 V",
    "",
  ],
  [
    "jeemain",
    "physics",
    53,
    "The fundamental frequency of vibration of a string stretched between two rigid support is 50 Hz. The mass of the string is 18 g and its linear mass density is 20 g/m. The speed of the transverse waves so produced in the string is -1 ms.",
    2024,
    false,
    "",
    "50",
    "63",
    "70",
    "80",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Find Length: L = Mass / Linear Density = 0.9 m Find Tension: Use f = (1/2L) * √(T/μ) to find T ≈ 81 N Find Wave Speed: v = √(T/μ) = 63 m/s Answer: 63 m/s",
    "",
  ],
  [
    "jeemain",
    "physics",
    54,
    "As per given figure A, B and C are the first, second and third excited energy level of hydrogen atom respectively. If the ratio of the two wavelengths",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736683813/Q.54_neydan.jpg",
    "4:9",
    "9:4",
    "5:7",
    "20:7",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Key: Wavelength ratio (λ₁/λ₂) is inversely proportional to the energy difference ratio (ΔE₂/ΔE₁). Calculate ΔE: Use the formula for energy levels in hydrogen. Find Ratio: λ₁/λ₂ = ΔE₂/ΔE₁ = 20/7",
    "",
  ],
  [
    "jeemain",
    "physics",
    55,
    "A solid sphere and a solid cylinder of same mass and radius are rolling on a horizontal surface without slipping. The ratio of their radius of gyrations respectively (ksph: keyl) is 2:√x, then value of x is",
    2024,
    false,
    "",
    "1",
    "2",
    "3",
    "5",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Radius of Gyration: Describes how mass is distributed. Formulas: k_sphere = √(2/5)R, k_cylinder = √(1/2)R Ratio: k_sph/k_cyl = √(4/5) = 2/√x Solve: x = 5",
    "",
  ],
  [
    "jeemain",
    "physics",
    56,
    "The refractive index of a transparent liquid filled in an equilateral hollow prism is √2. The angle of minimum deviation for the liquid will be",
    2024,
    false,
    "",
    "30°",
    "45°",
    "60°",
    "90°",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Formula: μ = (sin[(A + δ<sub>m</sub>)/2]) / sin(A/2) Substitute: √2 = sin[(60° + δ<sub>m</sub>)/2] / sin(30°) Solve: δ<sub>m</sub> = 30°",
    "",
  ],
  [
    "jeemain",
    "physics",
    57,
    "An electron in a hydrogen atom revolves around its nucleus with a speed of 6.76 × 100 ms¹ in an orbit of radius 0.52 A°. The magnetic field produced at the nucleus of the hydrogen atom is T.",
    2024,
    false,
    "",
    "5 T",
    "10 T",
    "12.5 T",
    "15 T",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "Find Current: I = qv / (2πr) Magnetic Field: B = (μ₀I) / (2r) Substitute and Calculate: B ≈ 12.5 T",
    "",
  ],
  [
    "jeemain",
    "physics",
    58,
    "There is an air bubble of radius 1.0 mm in a liquid of surface tension 0.075 Nm¹ and density 1000 kg m³ at a depth of 10 cm below the free surface. The amount by which the pressure inside the bubble is greater is than the atmospheric Pa (g = 10 ms²) pressure",
    2024,
    false,
    "",
    "1000 Pa",
    "1300 Pa",
    "1500 Pa",
    "2000 Pa",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Excess Pressure: Surface Tension: 4S/R = 300 Pa Hydrostatic: ρgh = 1000 Pa Total: 300 Pa + 1000 Pa = 1300 Pa",
    "",
  ],
  [
    "jeemain",
    "physics",
    59,
    "A block of mass 10 kg is moving along x-axis under the action of force F = 5x N. The work done by the force in moving the block from x 2m to 4m will be J.",
    2024,
    false,
    "",
    "15 J",
    "20 J",
    "25 J",
    "30 J",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Work Done: W = ∫ F dx = ∫ (5x) dx = (5/2) * x² Calculate: W = (5/2) * (4² - 2²) = 30 J",
    "",
  ],
  [
    "jeemain",
    "physics",
    60,
    "In the given figure the total charge stored in the combination of capacitors is 100 µC. The value of 'x' is",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736686449/Q.60_ivnozd.jpg",
    "1 μF",
    "2 μF",
    "3 μF",
    "4 μF",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Find C_eq: C_eq1 = (2x) / (2 + x) (for C1 and C2 in series) C_eq = C_eq1 + C3 Use Q = C_eq * V: 100 μC = C_eq * 10 V Solve for x: x = -2.8 μF (Not physically possible)",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    61,
    "Match List I with List II:",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736686795/Q.61_uc9lev.jpg",
    "(A)-(III), (B)-(I), (C)-(IV), (D)-(II)",
    "(A)-(III), (B)-(IV), (C)-(II), (D)-(1)",
    "(A)-(IV), (B)-(I), (C)-(II), (D)-(III)",
    "(A)-(II), (B)-(III), (C)-(IV), (D)-(1)",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Tetrafluoroethene: Polymerizes to form Teflon. \n Acrylonitrile: Polymerizes to form Orlon (a type of acrylic fiber). \n Caprolactam: Polymerizes to form Nylon-6. \n Isoprene: Polymerizes to form Natural Rubber.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    62,
    "The product formed in the following multistep reaction is:",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736687187/Q.62_np1ybc.jpg",
    "CH-CH2-CH-CH,",
    "CH3-CH2-CH2-CH2-OH",
    "CH3-CH2-C-OCH-OH",
    "CH3-C-CH-CH",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Hydroboration-Oxidation: Converts alkene to alcohol (anti-Markovnikov). \n PCC Oxidation: Oxidizes primary alcohol to aldehyde. \n Grignard Reaction: Forms a secondary alcohol.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    63,
    "The possibility of photochemical smog formation will be minimum at",
    2024,
    false,
    "",
    "Kolkata in October",
    "Mumbai in May",
    "New-Delhi in August (Summer)",
    "Srinagar, Jammu and Kashmir in January",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Photochemical Smog: Forms in the presence of sunlight, high temperatures, and high levels of nitrogen oxides and hydrocarbons. Minimum Formation:Srinagar in January (Winter): Low sunlight intensity and low temperatures in winter minimize the conditions for photochemical smog formation.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    64,
    "Which one of the following is not an example of calcination?",
    2024,
    false,
    "",
    "Fe₂O₃xH2O→ Fe2O3 + xH₂O",
    "CaCO, CaO+CO₂",
    "CaCO, MgCO, CaO+MgO+2CO₂",
    "2PbS+30→2PbO +2SO₂",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Calcination involves heating solids at high temperatures in limited air to cause thermal decomposition or remove volatiles. Key: High heat, limited air, often decomposes substances. Option (4) 2PbS + 3O₂ → 2PbO + 2SO₂ is NOT calcination. This is a roasting process, involving oxidation with excess air.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    65,
    "Consider the following statements: (A) NF3 molecule has a trigonal planar structure. (B) Bond length of N₂ is shorter than 02. (C) Isoelectronic molecules or ions have identical bond order. (D) Dipole moment of H2S is higher than that of water molecule. Choose the correct answer from the option below:",
    2024,
    false,
    "",
    "(A) and (D) are correct",
    "(C) and (D) are correct",
    "(A) and (B) are correct",
    "(B) and (C) are correct",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Calcination: High heat, limited air, often decomposes substances. Not Calcination: Roasting (like 2PbS + 3O₂ → 2PbO + 2SO₂) involves oxidation with excess air. Correct Answer: (4) (B) and (C) are correct.(B) True: N₂ (triple bond) has a shorter bond than O₂ (double bond). (C) False: Isoelectronic species can have different bond orders. (A) False: NF₃ is trigonal pyramidal. (D) False: H₂O has a higher dipole moment than H₂S.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    66,
    "Consider the following sequence of reactions:",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736708223/Q.66_ib7owc.jpg",
    "",
    "",
    "",
    "",
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736708258/ans.66_1_lsjefs.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736708489/ans.66_2_dl54ms.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736708514/ans.66_3_hgaqjz.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736708630/ans.66_4_mdcx3c.jpg",
    "B",
    false,
    "The reaction sequence involves a diazotization reaction followed by a coupling reaction. Diazotization: Aniline reacts with NaNO₂ and HCl at 0-5°C to form diazonium salt 'A'. Coupling: The diazonium salt 'A' reacts with N,N-dimethylaniline to form the azo compound 'B'. In this coupling reaction, the diazonium salt acts as an electrophile and attacks the para position of the N,N-dimethylaniline.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    67,
    "The number of POP bonds in H4P2O7, (HPO3)3 and P4O10 are respectively.",
    2024,
    false,
    "",
    "1, 3, 6",
    "0, 3, 6",
    "0, 3, 4",
    "1, 2, 4",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "H4P2O7 (Pyrophosphoric acid): There is one P-O-P bond. (HPO3)3 (Trimetaphosphoric acid): There are three P-O-P bonds. P4O10 (Tetraphosphorus decoxide): There are six P-O-P bonds.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    68,
    "Given below are two statements: Statement I: According to Bohr's model of hydrogen atom, the angular momentum of an electron in a given stationary state is quantised. Statement II: The concept of electron in Bohr's orbit, violates the Heisenberg uncertainty principle. In the light of the above statements, choose the most appropriate answer from the options given below: ",
    2024,
    false,
    "",
    "Both Statement I and Statement II are correct.",
    "Statement I is correct but Statement II is incorrect.",
    "Statement I is incorrect but Statement II is correct",
    "Both Statement I and Statement II are incorrect.",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Statement I: Bohr's model postulates that the angular momentum of an electron in a stable orbit around the nucleus is quantized. This means it can only take on specific, discrete values, not any arbitrary value. Statement II: The Heisenberg Uncertainty Principle states that it's impossible to simultaneously know both the exact position and momentum1 (which includes velocity) of a particle with certainty. Bohr's model, with its defined orbits, contradicts this principle by implying a precise knowledge of both the electron's position and momentum within those orbits.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    69,
    "Decreasing order of reactivity towards electrophilie substitution for the following compounds is:",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736745599/Q.69_qiwmlg.jpg",
    "c>b>a>d>e",
    "e>d>a>b>c",
    "a>d>e>b>c",
    "d>a>e>c>b",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "The order of reactivity is determined by electron-donating/withdrawing groups: Electron-donating groups (EDG): Increase reactivity (e.g., -OCH3, -NH2, -CH3) Electron-withdrawing groups (EWG): Decrease reactivity (e.g., -CF3) Therefore, the order is: -OCH3 > -NH2 > -CH3 > benzene > -CF3 (most reactive to least reactive)",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    70,
    "Which of the following statement(s) is/are correct? (A) The pH of 1 × 10 M HCl solution is 8. 2- (B) The conjugate base H2PO4 is HPO4. (C) Kw increases with increase in temperature. W (D) When a solution of weak monoprotic acid is titrated against a strong base at half 1 neutralisation point, pH = pK 2 Choose the correct answer from the option given below.",
    2024,
    false,
    "",
    "(B), (C), (D)",
    "(A), (D)",
    "(A), (B), (C)",
    "(B), (C)",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "(A) Incorrect: pH of 10^-2 M HCl is 2, not 8. (B) Correct: Conjugate base of H2PO4- is HPO4^2-. (C) Correct: Kw increases with temperature. (D) Correct: At half-neutralization of a weak acid, pH = pKa.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    71,
    "Given below are two statements: One is labelled as Assertion A and the other is labelled as Reason R: Assertion (A) BeCl2 and MgCl2 produce characteristic flame. Reason (R): The excitation energy is high in BeCl2 and MgCl2 In the light of the above statements, choose the correct answer from the option given below:",
    2024,
    false,
    "",
    "Both (A) and (R) are true but (R) is NOT the correct explanation of (A)",
    "(A) is false but (R) is true",
    "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "(A) is true but (R) is false.",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Assertion (A): BeCl2 and MgCl2 produce characteristic flames. This statement is true. When heated in a flame, compounds of beryllium and magnesium impart a characteristic color to the flame. BeCl2 gives a green flame, while MgCl2 gives a bright white flame. Reason (R): The excitation energy is high in BeCl2 and MgCl2. This statement is false. The excitation energy required for these compounds to emit visible light is relatively low, not high.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    72,
    "In the below conversion the correct sequence of reagents to be added is",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736746833/Q.72_izhy6j.jpg",
    "(i) Fe/H⁺, (ii) HONO, (iii) CuCl, (iv) KMnO4, (v) B",
    "(i) KMnO4, (ii) Br2/Fe, (iii) Fe/H+, (iv) Cl2",
    "(i) Br2/Fe, (ii) Fe/H+, (iii) HONO, (iv) CuCl, (v) KMnO4",
    "(i) Br2/Fe, (ii) Fe/H+, (iii) KMnO4, (iv) Cl2",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Br2/Fe: Bromination Fe/H+: Nitro group reduction HONO: Diazonium salt formation CuCl: Sandmeyer reaction (Cl substitution) KMnO4: Methyl group oxidation",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    73,
    "major product 'A' formed in the below reaction is",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747572/Q.73_ques_re66az.jpg",
    "",
    "",
    "",
    "",
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747600/Q.73_ans_1_h3lkmk.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747704/Q.73_ans_2_h0ltf2.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747723/Q.73_ans_3_hjcqf1.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747743/Q.73_ans_4_prajaq.jpg",
    "A",
    false,
    "The major product is formed by Markovnikov addition of water to the alkene, meaning the -OH group attaches to the more substituted carbon.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    74,
    "Which is not true for arginine?",
    2024,
    false,
    "",
    "It is a crystalline solid.",
    "It is associated with more than one pK, values",
    "It has a fairly high melting point.",
    "It has high solubility in benzene.",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Arginine is polar and not soluble in benzene (nonpolar).",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    75,
    "During water-gas shift reaction",
    2024,
    false,
    "",
    "carbon monoxide is oxidized to carbon dioxide.",
    "carbon is oxidized to carbon monoxide.",
    "carbon dioxide is reduced to carbon monoxide.",
    "water is evaporated in presence of catalyst",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "CO + H₂O ⇌ CO₂ + H₂ CO is oxidized to CO₂ H₂O is reduced to H₂",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    76,
    "For a good quality cement, the ratio of silica to alumina is found to be",
    2024,
    false,
    "",
    "3",
    "4.5",
    "2",
    "1.5",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "For a good quality cement, the ideal silica-to-alumina (SiO₂/Al₂O₃) ratio is around 2 to 4.5. Therefore, the most suitable answer from the given options is (2) 4.5",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    77,
    "Which of the following statement is correct for paper chromatography?",
    2024,
    false,
    "",
    "Water present in the mobile phase gets absorbed by the paper which then forms the stationary phase.",
    "Water present in the pores of the paper forms the stationary phase.",
    "Paper sheet forms the stationary phase.",
    "Paper and water present in its pores together form the stationary phase.",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "In paper chromatography: Stationary phase: Paper + water in its pores Mobile phase: Liquid solvent",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    78,
    "The major product formed in the Friedel-Craft acylation of chlorobenzene is.",
    2024,
    false,
    "",
    "",
    "",
    "",
    "",
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736750203/Q.78_ans__rfq0zb.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747704/Q.73_ans_2_h0ltf2.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747723/Q.73_ans_3_hjcqf1.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736747743/Q.73_ans_4_prajaq.jpg",
    "A",
    false,
    "In Friedel-Crafts acylation of chlorobenzene, the acyl group (COCH3) preferentially directs to the para position due to steric hindrance and electronic effects. 1 ",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    79,
    "The complex with highest magnitude of crystal field splitting energy (A) is",
    2024,
    false,
    "",
    "[Cr(OH2)6]3+",
    "[Ti(OH2)6]3+",
    "[Fe(OH2)6]3+",
    "[Mn(OH2)6]3+",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "[Fe(OH₂)]³⁺ has the highest CFSE due to Fe³⁺'s higher oxidation state.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    80,
    " Which of the following expressions is correct in case of a CsCl unit cell (edge length'a')?",
    2024,
    false,
    "",
    "Ics +Cr = Cs a √2",
    "cst+cr = a",
    "++C Cs CT √3 = a 2",
    "+c= a 2",
    false,
    "",
    "",
    "",
    "",
    "C",
    false,
    "In a CsCl unit cell: Cs+ ion is at the body center. Cl- ion is at the corner of the cube. The relationship between the ionic radii of Cs+ and Cl- and the edge length (a) of the unit cell is given by: rCs + rCl = a √3 / 2",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    81,
    "The homoleptic and octahedral complex of Co2+ and H₂O has set of orbitals. unpaired electron(s) in the t2g",
    2024,
    false,
    "",
    "0",
    "1",
    "2",
    "3",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "o2+ has a d7 electronic configuration. H2O is a weak-field ligand, leading to high-spin complexes. In an octahedral field, the d orbitals split into t2g and eg sets.According to Hund's rule, electrons will fill the orbitals singly before pairing. In a high-spin d7 complex, there will be three unpaired electrons in the t2g orbitals.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    82,
    "The volume (in mL) of 0.1 M AgNO3 required for complete precipitation of chloride ions present in 20 mL of 0.01 M solution of [Cr(H2O)5CI]Cl₂ as silver chloride is",
    2024,
    false,
    "",
    "2 mL",
    "6 mL",
    "8 mL",
    "4 mL",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Calculate moles of Cl- ions: 0.01 M * 20 mL * 2 = 0.0004 mol Calculate volume of 0.1 M AgNO3: 0.0004 mol / 0.1 M = 4 mL",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    83,
    "The total change in the oxidation state of manganese involved in the reaction of KMnO4 and potassium iodide in the acidic medium is",
    2024,
    false,
    "",
    "1",
    "2",
    "3",
    "5",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    84,
    "In Chromyl chloride, the oxidation state of chromium is (+)",
    2024,
    false,
    "",
    "+2",
    "+3",
    "+4",
    "+6",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "In Chromyl Chloride (CrO₂Cl₂), the oxidation state of Chromium is +6. This is determined by balancing the oxidation states of all atoms in the compound.",
    "",
  ],
  [
    "jeemain",
    "maths",
    85,
    "The total number of isoelectronic species from the given set is 02,F,Al, Mg2+, Na+, O+, Mg, Al,F",
    2024,
    false,
    "",
    "2",
    "3",
    "4",
    "5",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Isoelectronic species have the same number of electrons. O²⁻, F⁻, Na⁺, and Mg²⁺ all have 10 electrons. Al³⁺ also has 10 electrons.",
    "",
  ],
  [
    "jeemain",
    "maths",
    86,
    "The vapour pressure of 30% (w/v) aqueous solution of glucose is mm Hg at 25°C. [Given The density of 30% (w/v), aqueous solution of glucose is 1.2 g cm³ and vapour pressure of pure water is 24 mm Hg.] (Molar mass of glucose is 180 g mol¹.)",
    2024,
    false,
    "",
    "22.8 mm Hg",
    "23.2 mm Hg",
    "23.6 mm Hg",
    "24.0 mm Hg",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "Calculate moles of glucose and water. Calculate mole fraction of water. Apply Raoult's Law: P_solution = X_water * P_water",
    "",
  ],
  [
    "jeemain",
    "maths",
    87,
    "Major products A and B formed in the following reaction sequence, are",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736758354/Q.87_ques_kphhcr.jpg",
    "",
    "",
    "",
    "",
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736758493/Q.87_ans_1_q0sii5.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736759209/Q.87_ans_2_dj2jtc.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736759222/Q.87_ans_3_q9ajan.jpg",
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736759315/Q.87_ans_4_ie81p5.jpg",
    "A",
    false,
    "Reaction with PBr3: Converts alcohols to alkyl bromides. Reaction with Alcoholic KOH: Promotes dehydrohalogenation (elimination) reactions, leading to the formation of alkenes. Zaitsev's Rule: In elimination reactions, the major product is the alkene with the most substituted double bond.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    88,
    "Identify the major product C formed in the following reaction sequence:",
    2024,
    true,
    "https://res.cloudinary.com/dfbm6gumx/image/upload/v1736759848/Q.88_c8gtgo.jpg",
    "propylamine",
    "butylamine",
    "butanamide",
    "x-bromobutanoic acid",
    false,
    "",
    "",
    "",
    "",
    "A",
    false,
    "Reaction with PBr3: Converts alcohols to alkyl bromides. Reaction with Alcoholic KOH: Promotes dehydrohalogenation (elimination) reactions, leading to the formation of alkenes. Zaitsev's Rule: In elimination reactions, the major product is the alkene with the most substituted double bond.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    89,
    "During the preparation of Mohr's salt solution (Ferrous ammonium sulphate), which of the following acid is added to prevent hydrolysis of Fe* ion?",
    2024,
    false,
    "",
    "dilute hydrochloric acid",
    "concentrated sulphuric acid",
    "dilute nitric acid",
    "dilute sulphuric acid",
    false,
    "",
    "",
    "",
    "",
    "D",
    false,
    "Hydrolysis of Fe2+ ions: In aqueous solution, Fe2+ ions tend to undergo hydrolysis, forming a brown precipitate of Fe(OH)2. Role of Dilute Sulfuric Acid: Adding dilute sulfuric acid to the solution provides a source of H+ ions.    These H+ ions suppress the hydrolysis of Fe2+ ions by reacting with the hydroxide ions (OH-) produced during hydrolysis. This helps to maintain the stability of the ferrous ions in solution.",
    "",
  ],
  [
    "jeemain",
    "chemistry",
    90,
    "Consider the following reaction in a sealed vessel at equilibrium with concentrations of N2=3.0×10-3 M, O2 = 4.2 x 10 M and NO 2.8 × 10-3 М. 2NO(g) N2(g) + 02(0) If 0.1 mol L-1 of NO(g) is taken in a closed vessel, what will be degree of dissociation (a) of NO(g) at equilibrium?",
    2024,
    false,
    "",
    "0.00889",
    "0.0889",
    "0.8889",
    "0.717",
    false,
    "",
    "",
    "",
    "",
    "B",
    false,
    "1. Calculate Kc: Kc = [NO]^2 / ([N2] * [O2]) 2. Set up ICE table: 2NO(g) ⇌ N2(g) + O2(g) Initial: 0.1 M, 0 M, 0 M Change: -2x M, +x M, +x M Equilibrium: 0.1 - 2x M, x M, x M 3. Substitute into Kc expression and solve for x. 4. Calculate degree of dissociation (α): α = (moles of NO dissociated) / (initial moles of NO) α = 2x / 0.1 Answer: α = 0.0889",
    "",
  ],
];
