import 'package:flutter/material.dart';

const quotes = [
  "The whole of life is a test, a trial of what is in us, so arranged by God himself." ,
   "We are not so to live as if we had nothing but a body." ,
  "The two most important days in your life are the day you are born and the day you find out why." ,
  "We should employ our passions in the service of life, not spend life in the service of our passions." ,
  "Let us live as people who are prepared to die, and die as people who are prepared to live." ,
  "Let us endeavour so to live that when we come to die even the undertaker will be sorry." ,
  "No one can live well until they can die well." ,
  "Take care of your life and the Lord will take care of your death." ,
   "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live." ,
  "Life can only be enjoyed as one acquires a true perspective of life and death and of the real purpose of life." ,
  "If you want to live a happy life, tie it to a goal, not to people or things." ,
  "Three things in life – your health, your mission, and the people you love. That’s it." ,
  "Be brave enough to live the life of your dreams according to your vision and purpose instead of the expectations and opinions of others." ,
  "The more you know who you are, and what you want, the less you let things upset you." ,
  "You can't go back and change the beginning, but you can start where you are and change the ending." ,
  "You couldn’t relive your life, skipping the awful parts, without losing what made it worthwhile. You had to accept it as a whole–like the world, or the person you loved." ,
   "Life is a question and how we live it is our answer." ,
   "See: it’s a never-ending upward spiral. And if you think at any point you’re allowed to stop climbing, I’m afraid you’re missing the point. Because the joy is in the climb itself." ,
   "Don’t be afraid of death; be afraid of an unlived life. You don’t have to live forever, you just have to live." ,
   "Life is not a problem to be solved, but a reality to be experienced." ,
   "Most of life is about searching, it’s not about doing. People spend too much time doing and not thinking about what they should be doing." ,
  "Care about what other people think and you will always be their prisoner." ,
   "No tree, it is said, can grow to heaven unless its roots reach down to hell." ,
  "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." ,
  "In the end, it’s not the years in your life that count. It’s the life in your years." ,
   "Some people never go crazy. What truly horrible lives they must lead." ,
   "To live is the rarest thing in the world. Most people exist, that is all." ,
  "You don’t get to choose how you’re going to die. Or when. But you can decide how you’re going to live now." ,
  "Not how long, but how well you have lived is the main thing." ,
  "Life is not a process of discovery, but a process of creation." ,
  "It’s not so much what we have in this life that matters. It’s what we do with what we have." ,
   "Keep smiling, because life is a beautiful thing and there’s so much to smile about." ,
  "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it." ,
  "A man can fail many times, but he isn’t a failure until he begins to blame somebody else." ,
  "It's not what we have in life but who we have in our life that matters." ,
  "Life always waits for some crisis to occur before revealing itself at its most brilliant." ,
   "Life is really simple, but men insist on making it complicated." ,
  "Life is like a coin. You can spend it any way you wish, but you only spend it once." ,
  "The less you give a damn to negative people, the more peaceful your life will become." ,
  "Don't give it five minutes if you're not going to give it five years." ,
  "Dead people receive more flowers than the living ones because regret is stronger than gratitude." ,
  "I've failed over and over and over again in my life and that is why I succeed." ,
  "In every life, we have some trouble, but when you worry you make it double." ,
  "The hardest thing to learn in life is which bridge to cross and which bridge to burn." ,
  "Life doesn’t require that we be the best, only that we try our best." ,
  "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart." ,
  "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing." ,
   "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style." ,
    "Life's most persistent and urgent question is, 'What are you doing for others?'" ,
   "The flower that blooms in adversity is the rarest and most beautiful of all." ,
  "Life is short, live it. Love is rare, grab it. Anger is bad, dump it. Fear is awful, face it. Memory is sweet, cherish it." ,
  "The greatest discovery of any generation is that a human being can alter his life by altering his attitude." ,
  "Loving people live in a loving world. Hostile people live in a hostile world. Same world." ,
   "If you don't like the road you're walking, start paving another one." ,
  "Life is not a matter of holding good cards, but sometimes, playing a poor hand well." ,
  "The biggest adventure you can take is to live the life of your dreams." ,
  "A little foolishness, enough to enjoy life, and a little wisdom to avoid the errors, that will do." ,
   "A man who dares to waste one hour of time has not discovered the value of life." ,
  "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy." ,
  "By being yourself, you put something wonderful in the world that was not there before." ,
  "Life moves pretty fast. If you don’t stop and look around once in a while you could miss it." ,
   "The first half of life is devoted to forming a healthy ego, the second half is going inward and letting go of it." ,
  "Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness." ,
  "The only impossible journey is the one you never begin." ,
  "Life must be lived and curiosity kept alive. One must never, for whatever reason, turn his back on life." ,
  "Life is pretty simple: You do some stuff. Most fails. Some works. You do more of what works." ,
   "Don’t gain the world and lose your soul, wisdom is better than silver or gold." ,
  "Risks must be taken, because the greatest hazard in life is to risk nothing." ,
   "The most beautiful things in the world cannot be seen or even touched. They must be felt with the heart." ,
   "Take time to enjoy the little things, for one day you may look back and realize they were the big things." ,
  "It is better to be hated for what you are than to be loved for something you are not." ,
  "To do the useful thing, to say the courageous thing, to contemplate the beautiful thing: that is enough for one man’s life." ,
   "Life is short, and it is up to you to make it sweet." ,
  "Life is just the same as learning to swim. Do not be afraid of making mistakes, for there is no other way of learning how to live!" ,
   "Be willing to sacrifice what you think you have today for the life that you want tomorrow." ,
  "Lighten up, just enjoy life, smile more, laugh more, and don’t get so worked up about things." ,
  "The aim of life is to live, and to live means to be aware, joyously, drunkenly, serenely, divinely aware." ,
  "You must be the change you wish to see in the world." ,
   "Try to enjoy the great festival of life with other men!" ,
  "If life is a video game, the graphics are great, but the plot is confusing and the tutorial is way too long." ,
  "Life is so short. I would rather sing one song than interpret the thousand." ,
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't let yesterday take up too much of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The way to get started is to quit talking and begin doing.",
  "The best way to predict the future is to create it.",
  "Innovation distinguishes between a leader and a follower.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't let yesterday take up too much of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Don't let yesterday take up too much of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Believe you can and you're halfway there.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't let yesterday take up too much of today.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The harder you work, the luckier you get.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  " We cannot solve problems with the kind of thinking we employed when we came up with them.",
  " Learn as if you will live forever, live like you will die tomorrow.   —Mahatma Gandhi",
  " Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too. ",
  " When you give joy to other people, you get more joy in return. You should give a good thought to the happiness that you can give out.",
  " When you change your thoughts, remember to also change your world.   —Norman Vincent Peale",
  " It is only when we take chances that our lives improve. The initial and the most difficult risk we need to take is to become honest.",
  " Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together.",
  " Success is not final; failure is not fatal: It is the courage to continue that counts.",
  " It is better to fail in originality than to succeed in imitation.  ",
  " The road to success and the road to failure are almost exactly the same.",
  " Success usually comes to those who are too busy to be looking for it.",
  " Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. ",
  " Nothing in the world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race.",
  " There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind. ",
  " Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable. ",
  " I never dreamed about success. I worked for it.   —Estée Lauder",
  " The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  " Don’t let yesterday take up too much of today.   —Will Rogers",
  " You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
  " If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
  " Experience is a hard teacher because she gives the test first, the lesson afterward.",
  " To know how much there is to know is the beginning of learning to live.",
  " Goal setting is the secret to a compelling future.",
  " Concentrate all your thoughts upon the work in hand. The sun’s rays do not burn until brought to a focus.",
  " Either you run the day or the day runs you. ",
  " I’m a great believer in luck, and I find the harder I work, the more I have of it. ",
  " When we strive to become better than we are, everything around us becomes better too. ",
  " Opportunity is missed by most people because it is dressed in overalls and looks like work. ",
  " Setting goals is the first step in turning the invisible into the visible. ",
  " Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it. ",
  " Women challenge the status quo because we are never it.   —Cindy Gallop",
  " We don’t just sit around and wait for other people. We just make, and we do.",
  " Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. ",
  " The strongest actions for a woman is to love herself, be herself and shine amongst those who never believed she could. ",
  " Whenever you see a successful woman, look out for three men who are going out of their way to try to block her.",
  " Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore. ",
  " The thing women have yet to learn is nobody gives you power. You just take it.",
  " If they don’t give you a seat at the table, bring a folding chair. ",
  " I raise up my voice—not so that I can shout, but so that those without a voice can be heard. … We cannot all succeed when half of us are held back. ",
  " When a woman becomes her own best friend, life is easier.  ",
  " If you want something said, ask a man; if you want something done, ask a woman.   ",
  " We need women at all levels, including the top, to change the dynamic, reshape the conversation, to make sure women’s voices are heard and heeded, not overlooked and ignored. ",
  " It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent. ",
  " Women must learn to play the game as men do. ",
  " I swear, by my life and my love of it, that I will never live for the sake of another man, nor ask another man to live for mine.",
  " He who conquers himself is the mightiest warrior. ",
  " Try not to become a man of success, but rather become a man of value. ",
  " One man with courage makes a majority. ",
  " One secret of success in life is for a man to be ready for his opportunity when it comes. ",
  " A man who has committed a mistake and doesn’t correct it is committing another mistake. ",
  " The successful man will profit from his mistakes and try again in a different way.  ",
  " A successful man is one who can lay a firm foundation with the bricks others have thrown at him.  ",
  " He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. ",
  " You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. ",
  " Education is the most powerful weapon which you can use to change the world. ",
  " The most difficult thing is the decision to act; the rest is merely tenacity.",
  " You’ll find that education is just about the only thing lying around loose in this world, and it’s about the only thing a fellow can have as much of as he’s willing to haul away.",
  " Take the attitude of a student, never be too big to ask questions, never know too much to learn something new. ",
  " You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. ",
  " Education is the most powerful weapon which you can use to change the world. ",
  " The most difficult thing is the decision to act; the rest is merely tenacity.",
  " You’ll find that education is just about the only thing lying around loose in this world, and it’s about the only thing a fellow can have as much of as he’s willing to haul away.",
  " Take the attitude of a student, never be too big to ask questions, never know too much to learn something new. ",
  "Believe you can, and you're halfway there.",
  "Don't limit your challenges. Challenge your limits.",
  "Your only limit is your mind.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts",
  "Be yourself; everyone else is already taken.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Act as if what you do makes a difference. It does.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Confidence comes not from always being right but from not fearing to be wrong.",
  "Be the change that you wish to see in the world.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don't watch the clock; do what it does. Keep going.",
  "Hardships often prepare ordinary people for an extraordinary destiny." ,
  "You miss 100% of the shots you don’t take.",
  "Fall seven times and stand up eight.",
  "Do something today that your future self will thank you for.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The best way to get started is to quit talking and begin doing.",
  "Work like there is someone working 24 hours a day to take it away from you.",
  "The road to success is always under construction.",
  "Don't be afraid to dream big; the fear of failure is the harbinger of success.",
  "Don't limit your challenges. Challenge your limits.",
  "Your only limit is your mind.",
  "It does not matter how slowly you go as long as you do not stop.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Every accomplishment starts with the decision to try.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you’ve ever wanted is on the other side of fear." ,
  "Pain is temporary. Quitting lasts forever.",
  "Rock bottom became the solid foundation on which I rebuilt my life.",
  "Courage is resistance to fear, mastery of fear – not absence of fear.",
  "Don’t let what you cannot do interfere with what you can do." ,
  "A winner is a dreamer who never gives up." ,
  "Perseverance is not a long race; it is many short races one after the other.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "You don’t drown by falling in the water; you drown by staying there.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Great things are done by a series of small things brought together.",
  "Do what you can with all you have, wherever you are.",
  "Persistence guarantees that results are inevitable.",
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
  "Small progress is still progress.",
  "Dream big and dare to fail.",
  "Don’t wait. The time will never be just right.",
  "Start where you are. Use what you have. Do what you can.",
  "The future depends on what you do today.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "If opportunity doesn’t knock, build a door.",
  "Opportunities don't happen. You create them.",
  "Do one thing every day that scares you.",
  "If you’re going through hell, keep going.",
  "What you do today can improve all your tomorrows.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Change is the end result of all true learning.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "In the middle of every difficulty lies opportunity." ,
  "Failure is the opportunity to begin again more intelligently." ,
  "Be a student as long as you still have something to learn, and this will mean all your life.",
  "A mind is like a parachute. It doesn’t work if it is not open.",
  "The expert in anything was once a beginner." ,
  "Learning never exhausts the mind.",
  "An investment in knowledge pays the best interest.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "Don’t count the days. Make the days count.",
  "The best way out is always through.",
  "Life isn’t about finding yourself. It’s about creating yourself.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Success usually comes to those who are too busy to be looking for it.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "No pressure, no diamonds.",
  "Turn your wounds into wisdom.",
  "Success doesn’t just find you. You have to go out and get it.",
  "You are never too old to set another goal or to dream a new dream." ,
  "Happiness depends upon ourselves.",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
  "The only way to do great work is to love what you do.",
  "Believe in your infinite potential. Your only limitations are those you set upon yourself.",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "You are capable of more than you know.",
  "Stop being afraid of what could go wrong and start being excited about what could go right.",
  "Every day may not be good, but there is something good in every day.",
  "You are the artist of your life. Don't give the paintbrush to anyone else.",
  "Do not wait; the time will never be 'just right.' Start where you stand.",
  "Don’t count the hours you put in. Put in the hours that count.",
  "Without hard work, nothing grows but weeds." ,
  "Effort only fully releases its reward after a person refuses to quit.",
  "Don't stop when you're tired. Stop when you're done.",
  "Work harder than you think you did yesterday.",
  "Great things are not done by impulse, but by a series of small things brought together.",
  "There is no substitute for hard work." ,
  "A little progress each day adds up to big results.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Success isn’t always about greatness. It’s about consistency. Consistent hard work leads to success." ,
  "Success is not the key to happiness. Happiness is the key to success.",
  "The secret of success is to do the common things uncommonly well.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "If you don’t build your dream, someone else will hire you to help build theirs.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Don’t be afraid to give up the good to go for the great.",
  "Success is not in what you have, but who you are." ,
  "Victory is sweetest when you’ve known defeat.",
  "The greater the obstacle, the more glory in overcoming it.",
  "The best view comes after the hardest climb.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "We may encounter many defeats, but we must not be defeated.",
  "You don’t have to see the whole staircase, just take the first step.",
  "Your present circumstances don’t determine where you can go; they merely determine where you start.",
  "The struggles we endure today will be the 'good old days' we laugh about tomorrow.",
  "Turn your wounds into wisdom." ,
  "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
  "The best way to predict the future is to create it.",
  "Do not wait to strike till the iron is hot, but make it hot by striking." ,
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Action is the foundational key to all success.",
  "The difference between a successful person and others is not a lack of strength, but a lack of will.",
  "Start where you are. Use what you have. Do what you can.",
  "It’s never too late to be what you might have been.",
  "Don't wish for it. Work for it.",
  "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
  "Growth begins at the end of your comfort zone.",
  "The biggest risk is not taking any risk. In a world that’s changing really quickly",
  "Live life as if everything is rigged in your favor.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Enjoy the little things, for one day you may look back and realize they were the big things.",
  "Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain.",
  "To live will be an awfully big adventure.",
  "Your life does not get better by chance, it gets better by change.",
  "In the end, we only regret the chances we didn’t take.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Happiness is not by chance, but by choice.",
  "Be the change that you wish to see in the world.",
  "Fall seven times and stand up eight.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "You can’t go back and change the beginning, but you can start where you are and change the ending.",
  "Success doesn’t rush. The greatest reward is the journey!",
  "You miss 100% of the shots you don’t take.",
  "Be so good they can’t ignore you.",
  "The way to get started is to quit talking and begin doing.",
  "A winner is a dreamer who never gives up." ,
  "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
  "Courage is grace under pressure.",
  "It always seems impossible until it’s done.",
  "The comeback is always stronger than the setback.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Courage is the most important of all virtues because without courage, you can’t practice any other virtue consistently.",
  "Don’t limit your challenges. Challenge your limits.",
  "Adversity causes some men to break and others to break records.",
  "When the going gets tough, the tough get going.",
  "Sometimes you win, sometimes you learn.",
  "Opportunities are usually disguised as hard work, so most people don’t recognize them.",
  "Dream bigger. Do bigger.",
  "Your success will be determined by your own confidence and fortitude.",
  "The best preparation for tomorrow is doing your best today.",
  "Do what you can with all you have, wherever you are.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don't watch the clock; do what it does. Keep going.",
  "Go the extra mile. It’s never crowded there.",
  "Hard work beats talent when talent doesn’t work hard." ,
  "The secret of getting ahead is getting started.",
  "Everything you can imagine is real.",
  "Creativity is intelligence having fun.",
  "Don’t wait. The time will never be just right.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible." ,
  "If you’re not making mistakes, then you’re not doing anything.",
  "An idea is salvation by imagination.",
  "Inspiration does exist, but it must find you working.",
  "Creativity takes courage.",
  "If you have built castles in the air, your work need not be lost; that is where they should be. Now put foundations under them.",
  "Don’t be afraid to stand out.",
  "If we all did the things we are capable of, we would literally astound ourselves.",
  "Every accomplishment starts with the decision to try.",
  "Education is the most powerful weapon which you can use to change the world." ,
  "What we learn with pleasure we never forget.",
  "The best way to predict your future is to create it.",
  "The expert in anything was once a beginner.",
  "Do not fear failure but rather fear not trying.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "Life is a succession of lessons which must be lived to be understood.",
  "A mind that is stretched by a new experience can never go back to its old dimensions.",
  "Your future is created by what you do today, not tomorrow.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The best way to get started is to quit talking and begin doing.",
  "Do more things that make you forget to check your phone.",
  "Gratitude turns what we have into enough.",
  "Life is short. Smile while you still have teeth.",
  "The best way to cheer yourself up is to try to cheer somebody else up.",
  "Count your age by friends, not years. Count your life by smiles, not tears.",
  "The greatest wealth is not in the possession of others, but in the act of giving and receiving.",
  "The greatest danger of success is not the failure, but the fear of not trying.",
  "The only way to do great work is to love what you do." ,
  "The best way to find success is to believe in yourself.",
  "The best way to find out what you want is to ask for it.",
  "It does not matter how slowly you go as long as you do not stop.",
  "No act of kindness, no matter how small, is ever wasted.",
  "Knowing yourself is the beginning of all wisdom.",
  "The best way out is always through." ,
  "It is during our darkest moments that we must focus to see the light.",
  "Life isn’t about finding yourself. It’s about creating yourself.",
  "Happiness often sneaks in through a door you didn’t know you left open.",
  "The best way to get started is to quit talking and begin doing.",
  "The unexamined life is not worth living.",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
  "The man who moves a mountain begins by carrying away small stones.",
  "The sun himself is weak when he first rises and gathers strength and courage as the day gets on." ,
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Hope is being able to see that there is light despite all of the darkness.",
  "Even the darkest night will end, and the sun will rise." ,
  "Nothing is impossible. The word itself says 'I’m possible!'",
  "Somewhere, something incredible is waiting to be known.",
  "Light tomorrow with today.",
  "You do not find the happy life. You make it.",
  "Hope is the only thing stronger than fear.",
  "Storms make trees take deeper roots.",
  "The best way to get started is to quit talking and begin doing.",
  "The secret to getting ahead is getting started.",
  "The road to success is paved with the right footsteps.",
  "The greatest risk you take when you start something new is not the failure, but the doubts that you didn't take.",
  "If you can dream it, you can achieve it.",
  "The only way to do great work is to love what you do." ,
  "Believe you can and you’re halfway there.",
  "The only way to do great work is to love what you do.",
  "Fall seven times, stand up eight.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
   "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "You get what you give.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "With the new day comes new strength and new thoughts.",
  "Believe in yourself, take on your challenges, and dig deep to conquer fears.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Your passion is waiting for your courage to catch up.",
  "Great things never come from comfort zones.",
  "The way to get started is to quit talking and begin doing.",
  "Push yourself, because no one else is going to do it for you.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "In the middle of every difficulty lies opportunity.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Do what is right, not what is easy nor what is popular.",
  "You only live once, but if you do it right, once is enough.",
  "Do not wait for the perfect time and place to enter, for you are already onstage.",
  "If you cannot do great things, do small things in a great way.",
  "Do not let what you cannot do interfere with what you can do.",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "The bad news is time flies. The good news is you’re the pilot.",
  "We may encounter many defeats but we must not be defeated.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Courage is resistance to fear, mastery of fear—not absence of fear.",
  "If you're going through hell, keep going.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "Nothing will work unless you do.",
  "Your big opportunity may be right where you are now.",
  "It’s not whether you get knocked down; it’s whether you get up.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Do one thing every day that scares you.",
  "Be yourself; everyone else is already taken.",
  "Happiness is not by chance, but by choice.",
  "Life changes very quickly, in a very positive way, if you let it.",
  "Don’t wait. The time will never be just right.",
  "Don’t limit your challenges. Challenge your limits.",
  "If you don’t like the road you’re walking, start paving another one.",
  "Hustle beats talent when talent doesn’t hustle.",
  "Do what you love, love what you do, and deliver more than you promise.",
  "The journey of a thousand miles begins with one step.",
  "Dream big and dare to fail.",
  "Don’t wait for opportunity. Create it.",
  "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Everything you can imagine is real.",
  "Your life only gets better when you get better.",
  "It’s never too late to be what you might’ve been.",
  "Do what you can, with what you have, where you are.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "The secret to getting ahead is getting started.",
  "Your limitation—it’s only your imagination.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "Don’t tell people your plans. Show them your results.",
  "Work hard in silence, let your success be the noise.",
  "Dream it. Wish it. Do it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of amazing things.",
  "Believe in yourself and all that you are.",
  "Success is what happens after you have survived all your mistakes.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "Never regret anything that made you smile.",
  "Strive not to be a success, but rather to be of value.",
  "A little progress each day adds up to big results.",
  "The best revenge is massive success.",
  "Action is the foundational key to all success.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Believe in yourself, push your limits, and do whatever it takes to conquer your goals.",
  "Failure is the condiment that gives success its flavor.",
  "The best way to predict the future is to create it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Dream bigger. Do bigger.",
  "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
  "People who are crazy enough to think they can change the world are the ones who do.",
  "Great things are done by a series of small things brought together.",
  "If you believe it will work out, you’ll see opportunities. If you believe it won’t, you’ll see obstacles.",
  "Hard work keeps the wrinkles out of the mind and spirit.",
  "You can’t go back and change the beginning, but you can start where you are and change the ending.",
   "Do what you can with all you have, wherever you are.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
  "Don’t limit your challenges. Challenge your limits.",
  "Great things never come from comfort zones.",
  "Dream big and dare to fail.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Success is not in what you have, but who you are.",
  "Small daily improvements over time lead to stunning results.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The key to success is to focus on goals, not obstacles.",
  "Opportunities don't happen, you create them.",
  "Don’t wait. The time will never be just right.",
  "The future depends on what we do in the present.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you want to go fast, go alone. If you want to go far, go together.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Start where you are. Use what you have. Do what you can.",
  "You don't have to be great to start, but you have to start to be great.",
  "The journey of a thousand miles begins with one step.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Success is the result of preparation, hard work, and learning from failure.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Push yourself, because no one else is going to do it for you.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Work hard in silence, let your success be your noise.",
  "Don’t wait for opportunity. Create it.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Success is what happens after you have survived all your mistakes.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Success is not the absence of failure; it's the persistence through failure.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You must expect great things of yourself before you can do them.",
  "Your limitation—it’s only your imagination.",
  "The only way to do great work is to love what you do.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for the perfect moment. Take the moment and make it perfect.",
  "Opportunities don’t happen. You create them.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Do what you can, with what you have, where you are.",
  "The best way to predict the future is to create it.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "It’s never too late to be what you might have been.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "The only person you are destined to become is the person you decide to be.",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
  "Happiness depends upon ourselves.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Act as if what you do makes a difference. It does.",
  "Success is not in what you have, but who you are.",
  "The only time to be positive you've got the clear sailing is when you're on the beach.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Be so good they can’t ignore you.",
  "Success usually comes to those who are too busy to be looking for it.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "A person who never made a mistake never tried anything new.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "It always seems impossible until it’s done.",
  "In order to succeed, we must first believe that we can.",
  "The way to get started is to quit talking and begin doing.",
  "Do something today that your future self will thank you for.",
  "The difference between who you are and who you want to be is what you do.",
  "I can and I will. Watch me.",
  "Doubt kills more dreams than failure ever will.",
  "The only way to do great work is to love what you do.",
  "Everything you can imagine is real.",
  "You don’t have to be great to start, but you have to start to be great.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "If you want to achieve greatness stop asking for permission.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The best way to predict the future is to create it.",
  "You miss 100% of the shots you don’t take.",
  "Don’t be afraid to give up the good to go for the great.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Don’t be afraid to start over. It’s a brand new opportunity to rebuild what you want.",
  "There is no elevator to success, you have to take the stairs.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Don’t wait for the perfect moment. Take the moment and make it perfect.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall",
  "The only limit to our realization of tomorrow is our doubts of today",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only person you are destined to become is the person you decide to be.",
  "The difference between try and triumph is just a little umph!",
  "The only way to do great work is to love what you do.",
   "It is not how long but how well we live that matters." ,
  "Life is not a solo but a chorus. We live in relationships from cradle to grave." ,
  "Life is worth living better than most men live it." ,
  "Live your best, and act your best, and think your best each day, for there may be no tomorrows." ,
  "Everything in life is a test of character." ,
  "Life ought not merely to contain acts of worship, it should be an act of worship." ,
  "Be such a man, and live such a life, that if every man were such as you, and every life a life like yours, this earth would be God’s paradise." ,
  "The quality of life is more important than life itself." ,
  "Life is too short to be small." ,
  "The man who regards his own life and that of his fellow creatures as meaningless is not merely unfortunate but almost disqualified for life." ,
  "What makes life dreary is absence of motive. What makes life complicated is multiplicity of motive. What makes life victorious is singleness of motive." ,
  "Life is not measured by length but by depth. Birthdays tell us how long we have been on the road, not how far we have travelled." ,
  "Every man’s life is his opportunity of doing that which will make for him in eternity." ,
  "Sow an action and you reap a habit; sow a habit and you reap a character; sow a character and you reap a destiny." ,
  "The most important thing in life is to live your life for something more important than your life." ,
   "The end of life is not to be happy, nor to achieve pleasure and avoid pain, but to do the will of God, come what may." ,
  "Make sure the thing you are living for is worth dying for." ,
  "The seven ages of man: spills, drills, thrills, bills, ills, pills, wills." ,
  "We are here to add what we can to life, not to get what we can from it." ,
  "The whole of life is a test, a trial of what is in us, so arranged by God himself." ,
   "We are not so to live as if we had nothing but a body." ,
  "The two most important days in your life are the day you are born and the day you find out why." ,
  "We should employ our passions in the service of life, not spend life in the service of our passions." ,
  "Let us live as people who are prepared to die, and die as people who are prepared to live." ,
  "Let us endeavour so to live that when we come to die even the undertaker will be sorry." ,
  "No one can live well until they can die well." ,
  "Take care of your life and the Lord will take care of your death." ,
   "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live." ,
  "Life can only be enjoyed as one acquires a true perspective of life and death and of the real purpose of life." ,
  "If you want to live a happy life, tie it to a goal, not to people or things." ,
  "Three things in life – your health, your mission, and the people you love. That’s it." ,
  "Be brave enough to live the life of your dreams according to your vision and purpose instead of the expectations and opinions of others." ,
  "The more you know who you are, and what you want, the less you let things upset you." ,
  "You can't go back and change the beginning, but you can start where you are and change the ending." ,
  "You couldn’t relive your life, skipping the awful parts, without losing what made it worthwhile. You had to accept it as a whole–like the world, or the person you loved." ,
   "Life is a question and how we live it is our answer." ,
   "See: it’s a never-ending upward spiral. And if you think at any point you’re allowed to stop climbing, I’m afraid you’re missing the point. Because the joy is in the climb itself." ,
   "Don’t be afraid of death; be afraid of an unlived life. You don’t have to live forever, you just have to live." ,
   "Life is not a problem to be solved, but a reality to be experienced." ,
   "Most of life is about searching, it’s not about doing. People spend too much time doing and not thinking about what they should be doing." ,
  "Care about what other people think and you will always be their prisoner." ,
   "No tree, it is said, can grow to heaven unless its roots reach down to hell." ,
  "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." ,
  "In the end, it’s not the years in your life that count. It’s the life in your years." ,
   "Some people never go crazy. What truly horrible lives they must lead." ,
   "To live is the rarest thing in the world. Most people exist, that is all." ,
  "You don’t get to choose how you’re going to die. Or when. But you can decide how you’re going to live now." ,
  "Not how long, but how well you have lived is the main thing." ,
  "Life is not a process of discovery, but a process of creation." ,
  "It’s not so much what we have in this life that matters. It’s what we do with what we have." ,
   "Keep smiling, because life is a beautiful thing and there’s so much to smile about." ,
  "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it." ,
  "A man can fail many times, but he isn’t a failure until he begins to blame somebody else." ,
  "It's not what we have in life but who we have in our life that matters." ,
  "Life always waits for some crisis to occur before revealing itself at its most brilliant." ,
   "Life is really simple, but men insist on making it complicated." ,
  "Life is like a coin. You can spend it any way you wish, but you only spend it once." ,
  "The less you give a damn to negative people, the more peaceful your life will become." ,
  "Don't give it five minutes if you're not going to give it five years." ,
  "Dead people receive more flowers than the living ones because regret is stronger than gratitude." ,
  "I've failed over and over and over again in my life and that is why I succeed." ,
  "In every life, we have some trouble, but when you worry you make it double." ,
  "The hardest thing to learn in life is which bridge to cross and which bridge to burn." ,
  "Life doesn’t require that we be the best, only that we try our best." ,
  "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart." ,
  "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing." ,
   "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style." ,
    "Life's most persistent and urgent question is, 'What are you doing for others?'" ,
   "The flower that blooms in adversity is the rarest and most beautiful of all." ,
  "Life is short, live it. Love is rare, grab it. Anger is bad, dump it. Fear is awful, face it. Memory is sweet, cherish it." ,
  "The greatest discovery of any generation is that a human being can alter his life by altering his attitude." ,
  "Loving people live in a loving world. Hostile people live in a hostile world. Same world." ,
   "If you don't like the road you're walking, start paving another one." ,
  "Life is not a matter of holding good cards, but sometimes, playing a poor hand well." ,
  "The biggest adventure you can take is to live the life of your dreams." ,
  "A little foolishness, enough to enjoy life, and a little wisdom to avoid the errors, that will do." ,
   "A man who dares to waste one hour of time has not discovered the value of life." ,
  "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy." ,
  "By being yourself, you put something wonderful in the world that was not there before." ,
  "Life moves pretty fast. If you don’t stop and look around once in a while you could miss it." ,
   "The first half of life is devoted to forming a healthy ego, the second half is going inward and letting go of it." ,
  "Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness." ,
  "The only impossible journey is the one you never begin." ,
  "Life must be lived and curiosity kept alive. One must never, for whatever reason, turn his back on life." ,
  "Life is pretty simple: You do some stuff. Most fails. Some works. You do more of what works." ,
   "Don’t gain the world and lose your soul, wisdom is better than silver or gold." ,
  "Risks must be taken, because the greatest hazard in life is to risk nothing." ,
   "The most beautiful things in the world cannot be seen or even touched. They must be felt with the heart." ,
   "Take time to enjoy the little things, for one day you may look back and realize they were the big things." ,
  "It is better to be hated for what you are than to be loved for something you are not." ,
  "To do the useful thing, to say the courageous thing, to contemplate the beautiful thing: that is enough for one man’s life." ,
   "Life is short, and it is up to you to make it sweet." ,
  "Life is just the same as learning to swim. Do not be afraid of making mistakes, for there is no other way of learning how to live!" ,
   "Be willing to sacrifice what you think you have today for the life that you want tomorrow." ,
  "Lighten up, just enjoy life, smile more, laugh more, and don’t get so worked up about things." ,
  "The aim of life is to live, and to live means to be aware, joyously, drunkenly, serenely, divinely aware." ,
  "You must be the change you wish to see in the world." ,
   "Try to enjoy the great festival of life with other men!" ,
  "If life is a video game, the graphics are great, but the plot is confusing and the tutorial is way too long." ,
  "Life is so short. I would rather sing one song than interpret the thousand." ,
];