
//format of the list
//subject
//chapter
//int questionNumber
//question
//year
//bool: isquestionimage
//string: questionimage
//string: option1
//string: option2
//string: option3
//string: option4
//bool: isoptionimage
//imagelink: option1
//imagelink: option2
//imagelink: option3
//imagelink: option4
//string or bool: answer
//string + image: explanation
//bool: isexplanationimage
//String: image


List<List<dynamic>> chapter_1_11_set_1 = [
    [
        'maths',
        'Quadratic Equations',
        1,
        'If both the roots of the quadratic \n equation x ^ 2 - mx + 4 = 0 are real \n and distinct and they lie in the interval [1.5] \n then m lies in the interval',
        '2019',
        false,
        '',
        false,
        '(-5,-4)',
        '(3, 4)',
        '(4, 5]',
        '(5, 6)',
        false,
        '',
        '',
        '',
        '',
        'C',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        2,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        3,
        'Consider the quadratic equation c5. \n Let S be the set of all integral \n values of c for which one root \n  of the equation and its other \n root lies in the interval (2.3) \n (c - 5) * x ^ 2 - 2cx(c - 4) = 0 Then \n the number of elements in S is',
        '2019',
        false,
        '',
        false,
        '11',
        '18',
        '12',
        '10',
        false,
        '',
        '',
        '',
        '',
        'A',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        4,
        'The value of lambda, such that sum of the squares of the roots of the quadratic equation, x ^ 2 + (3 - lambda) * x + 2 = lambda',
        '2019',
        false,
        '',
        false,
        '2',
        '1',
        '15/8',
        '4/9',
        false,
        '',
        '',
        '',
        '',
        'A',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        5,
        'If lambda be the ratio of the roots of the quadratic equation in x, 3m ^ 2 * x ^ 2 + m(m - 4) * x + 2 = 0 then the least value of m for which 1/lambda_{s} = 1',
        '2019',
        false,
        '',
        false,
        '4 - 2sqrt(3)',
        '4 - 3sqrt(2)',
        '2 - sqrt(3)',
        '- 2 + sqrt(2)',
        false,
        '',
        '',
        '',
        '',
        'B',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        6,
        'The number of integral values of m\n  for which the quadratic expression, \n (1 + 2m) * x ^ 2 - 2(1 + 3m) * x +4(1+ m),\n  xeR, is always positive, is',
        '2019',
        false,
        '',
        false,
        '8',
        '3',
        '6',
        '7',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        7,
        'The number of real roots of the equation \n 5 + boxed |2^ * -1|=2^ * (2^ * -2)|',
        '2019',
        false,
        '',
        false,
        '4',
        '2',
        '1',
        '3',
        false,
        '',
        '',
        '',
        '',
        'C',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        8,
        'Let α and β be the roots of the \n equation x^2 - x - 1, if p(k) = (α)^k + (β)^k , k>=1 then which one of the following statement is not true ?',
        '2019',
        false,
        '',
        false,
        'p3 = p5 - p4',
        'p_{1}*p_{2}*p_{3} + p_{3} + p_{3} + p_{1}) = 26',
        'p5 = 11',
        'p5 = p2 . p3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        9,
        'Let & be the set of all real routs of the equation, 3^x * (3^x - 1) + 2 + |3^x - 1| + |3^x - 2| Then S',
        '2019',
        false,
        '',
        false,
        'Contains at least four elements',
        'Is a singleton',
        'Contains exactly two elements',
        'Contains at least four elements',
        false,
        '',
        '',
        '',
        '',
        'B',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        10,
        'Let a,b ∈ R x = 0 be such that the equation, a * x ^ 2 - 2bx + 5 = 0 has a repeated root α, which is also a root of the equation, x ^ 2 - 2bx - 10 * 0 is the other root of this equation, then α^2 + β^2 equal to',
        '2020',
        false,
        '',
        false,
        '25',
        '24',
        '26',
        '28',
        false,
        '',
        '',
        '',
        '',
        'A',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        11,
        'Consider the two sets: \n A = {m ∈ R: both the roots of x ^ 2 - (m + 1)\nx + m + 4 = 0 are real} and B = [- 3, 5) \n Which of the following is not true?',
        '2020',
        false,
        '',
        false,
        'A cap B = {- 3}',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        12,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        13,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        14,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        15,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        16,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        17,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        18,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        19,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        20,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        21,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
        'maths',
        'Quadratic Equations',
        22,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

    [
       'maths',
        'Quadratic Equations',
        23,
        'The number of all possible positive \n integral values of a \n for which the roots of \n the quadratic equation,\n 6x ^ 2 - 11x + a = 0 are \n rational numbers is',
        '2019',
        false,
        '',
        false,
        '4',
        '5',
        '2',
        '3',
        false,
        '',
        '',
        '',
        '',
        'D',
        '',
        false,
        '',
    ],

];

List<List<String>> chapter_1_11_set_2 = [
    [
       
    ],
];

List<List<String>> chapter_1_11_set_3 = [
    [
       
    ],
];

List<List<String>> chapter_2_11_set_1 = [
   [
     
   ],
];

List<List<String>> chapter_2_11_set_2 = [
   [
     
   ],
];

List<List<String>> chapter_2_11_set_3 = [
   [
     
   ],
];



List<List<dynamic>> chapter_9_11_set_1 = [
  [
    'maths',
    'Sequence and Series',
    1,
    'Let a, 2a be in AP such that sum (a_1 + a_2 + ... + a_11) = 416, and a_1 + a_11 * 66 = a_c1^2 = 140. Then m is equal to:',
    '2018',
    false,
    '',
    false,
    '34',
    '33',
    '66',
    '68',
    false,
    '',
    '',
    '',
    '',
    '1',
    'a_{1} + a_{2} + a_{1} + a_{12} + a_{10} = 416 y 1 = (y_{1} + xd) + (y_{1} + 3d) + (y_{1} + 12d) + (B_{1} + 4Bd) = 416 13 a_{1} + 4 * d(1 + 2 * 3 * 12) = 410 15 equiv plus/minus (4 * d * 12 * 13)/2 * 4 % 13 24 130416 3.+ 24d = 32 a_{1}*a_{62} = 66 a 1 +6d+ underline z 1 + 42d = 66 2ai + 50d + 66 A * 25d = 33 d = 1 a8 a ^ 2 + (a, d) ^ 2 + (a, 2d) ^ 2 +....,+(a r * 16c * t ^ 2 = 140m 17a|^ 2 +d^ 2 ( 1 ^ 2 + 2 ^ 2 +...+16^ 2 )+2ad ( 1 + 2 + 3 +...+16)=140m 17 * 64 + (16 * 17 * 33)/6 + (2 * 8 * 1 * 16 * 17)/2 = 140m 17 * 6d * 8 * 11 * 17 + 8 * 11 * 17 = 140m 17 * 16 + 22 * 17 * 2 * 16 * 17 = 35m 272 + 374 + 544 = 35m 1190 = 35m > m = 34',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    2,
    'Let A be the sum of the first 20 terms and B be the sum of the first 40 terms of the series: 1^2 + 2*2^2 + 3^2 + 2*4^2 + 5^2 + 2*6^2 + ... If 8 - 2A = 1002, then what is the value of A?',
    '2018',
    false,
    '',
    false,
    '464',
    '496',
    '232',
    '248',
    false,
    '',
    '',
    '',
    '',
    '1',
    '1 ^ 2 + 2.2 ^ 2 + 3 ^ 2 + 2.4 ^ 2 + 5 ^ 2 + 2.6 ^ 2 + A= 1 ^ 2 + 2.2 ^ 2 +...+20^ 2 =( 1 ^ 2 + 2 ^ 2 +...+20^ 2 )+(2^ 2 +4^ 2 +...+20^ 2 ) = (20.21 * 0.41)/6 +4. 10.11.21 6 = 20.21/6 * {41 + 22} = 70 * 63 = 4410   B= 1 ^ 2 + 2.2 ^ 2 +...+2.40^ 2 =( 1 ^ 2 + 2 ^ 2 +...+40^ 2 )+(2^ 2 +4^ 2 +...+40^ 2 ) (40.41 * 0.81)/6 + (4.2 * 0.21 * 0.41)/6 = 40.41/6 * (81 + 42) 40.41/6 * 123 + 20i +1 7=33620 E - 2A = 100lambda >620-8820 100 = 24800/100 * 248',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    3,
    'If a, b, c are three distinct real numbers in G.P. and a + b + c = xb, then x cannot be:',
    '2019',
    false,
    '',
    false,
    '2',
    '-3',
    '-2',
    '4',
    false,
    '',
    '',
    '',
    '',
    '2',
    ' a, b, c, are in GP b ^ 2 = ac cos a + b + c = xb c(x-1)b Now square it Rightarrow a ^ 2 + c ^ 2 + 2ac = (x - 1) ^ 2 * b ^ 2 Rightarrow a ^ 2 + c ^ 2 = (x - 1) ^ 2 * ac - 2ac Rightarrow a ^ 2 + c ^ 2 = ac{(x - 1) ^ 2 - 2} a ^ 2 * c ^ 2 are positive and b ac which is also positive so x ^ 2 - 2x - 1 would be positive but for x = 2 x ^ 2 - 2x -1| negative so x cannot take 2',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    4,
    'The sum of all two-digit positive numbers which, when divided by 7, yield a remainder of 2 or 5 is:',
    '2018',
    false,
    '',
    false,
    '1465',
    '1356',
    '1365',
    '1256',
    false,
    '',
    '',
    '',
    '',
    '3',
    '5= 16 + 23 + 30 + +93=654 5^ = 12 + 19 + 26 + +96=702 Required Sum6547021356',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    5,
    'Let x, y be positive real numbers and m, n be positive integers. What is the maximum value of the expression x^m * y^n (1 + x^2m)(1 + y^n)?',
    '2019',
    false,
    '',
    false,
    'sqrt(2)',
    '-sqrt(2)',
    '-1',
    '0',
    false,
    '',
    '',
    '',
    '',
    '1',
    'E- x^ prime prime y^ prime prime (1 + x ^ (2m))(1 + y ^ (2c)) = 1 (x^ -m +x^ m )(y^ -1 * y^ prime prime ) x^ prime prime +y^ prime prime 2 >=(x^ prime prime x^ - prime prime )^ 1/2 Rightarrow x^ prime prime +x^ prime prime >=2 Similarly y ^ - 1 + y ^ n >= 2 ( x ^ prime prime +x^ prime prime )(y^ prime prime +y^ prime prime )>=4 1/((x ^ m + x ^ (- m))(y ^ - 4 + y ^ n)) <= 1/4',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    6,
    'If the 19th term of a non-zero A.P. is zero, then its 49th term minus the 29th term is:',
    '2019',
    false,
    '',
    false,
    '0',
    '2',
    '-2',
    '4',
    false,
    '',
    '',
    '',
    '',
    '1',
    'Let first term and common difference of AP be a and d respectively t eg =a+18d=0 a = - 18d t eh t partial n = a+48d a+2Bd = (- 18d + 48d)/(- 18d + 28d) = (30d)/(10d) = 3 ',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    7,
    'If sin^4(α) + 4cos^4(β) + 2 = 4√2 * sin(α)cos(β), then cos(α + β) - cos(α - β) equals:',
    '2019',
    false,
    '',
    false,
    'sqrt(2)',
    '-sqrt(2)',
    '-1',
    '0',
    false,
    '',
    '',
    '',
    '',
    '4',
    'L_{0} = 3/1 alpha=4 cos^ 4 ( 1 + 2 = 4sqrt(2) cos beta = beta = [0, gamma] By AM GM inegality pi(2)^ * (n-4.65^ * (1+1+1 4 =( 3i * n ^ 4 * a * 4 cos^ * (1*1*1)^ * 3 cos^ (a-4 cos^ | beta + t + 1 >= 4sqrt(2) * sec(alpha)|cos beta| When cos 0 * 0 then inequality still holds but LH.S is positive than cos theta > 0 Here, L H.S.= RHS sin^4 alpha = 1ard * cos^4 beta = 1/4 alpha = pi/2 * ar * dB = pi/4 cos(a + beta) - cos(a - beta) cos(pi/2 + p) - r * cos(pi/2 - p) = sin beta - sin beta = - 2sin(pi/4) = - sqrt(2) Since a, b, c are in G.P b ^ 2 = ac Given, a * x ^ 2 + 2bx + c = 0',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    8,
    'If three distinct numbers a, b, c are in G.P. and the equations a * x^2 + 2bx + c = 0 and d * x^2 + 2ex + f = 0 have a common root, then which one of the following statements is correct?',
    '2019',
    false,
    '',
    false,
    'd, e, f are in A.P.',
    'd/a, e/b, f/c are in G.P.',
    'd, e, f are in G.P.',
    'd/a, e/b, f/c are in A.P.',
    false,
    '',
    '',
    '',
    '',
    '2',
    'a * x ^ 2 + 2sqrt(ac) * x + c = 0 (sqrt(a) * x + sqrt(c)) ^ 2 = 0 x = - sqrt(c/a) ax2bx+c=0 and dx2ex+1=0 have common root x=- sqrt c a must satisfy d * x ^ 2 + 2ex + t = 0 d * c/a + 2o(- sqrt(c/a)) + t = 0 d dt - 2e sqrt ac + t c =0 Rightarrow d/a - (2e)/b + t/c = 0 (2a)/b = a/a - t/c a/a, a/b , t c ara Rightarrow AP (50 - (7A)/2) * n + n ^ 2 * A/2 Common difference--2-A a_{10} = a_{1} + 49d (50 - 3A) + 49A = 50 + 46A So (d, a_{50}) = (A, 50 + 46A)',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    9,
    'Let a/4, 1/5, 1/5 be in AP. Let the sum of the first term of a non-constant AP be given by the formula S_n + (4(n - 1))/2 * A where A is the common difference of the AP. Then the correct value is:',
    '2015',
    false,
    '',
    false,
    '(A, 50 + 45A)',
    '(A, 30464)',
    '(50 + 45A)',
    '(A, 50 + 45A)',
    false,
    '',
    '',
    '',
    '',
    '3',
    '',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    10,
    'If the sum and product of the first three terms in an A.P. are 33 and 1155, respectively, then the value of the first term is:',
    '2015',
    false,
    '',
    false,
    '-26',
    '25',
    '-20',
    '-35',
    false,
    '',
    '',
    '',
    '',
    '1',
    ' Let terms be s - d, a, a + d 33311 Product of terms (a - d) * a(a + d) = 11(121 - d ^ 2) = 1155 Rightarrow 121 - d ^ 2 =105 Rightarrow d= pm4 d = 4 T_{x} = 7 matrix T y =11\\ T y =15 matrix | Rightarrow T t1 - T_{s} + 10d = 7 + 10(4) - 47 dd = - 4 T_{1} - 15 matrix T 2 &=11\\ T 1 &-7 matrix  Rightarrow T_{11} = T_{1} + 10d = 15 + 10(- 4) = - 25',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    11,
    'If a1, a2, ..., a11 are in AP and a10 = 14, then the sum a1 + a2 + a11 + a12 is equal to:',
    '2019',
    false,
    '',
    false,
    '38',
    '64',
    '76',
    'None of the above',
    false,
    '',
    '',
    '',
    '',
    '3',
    '3(a_{1} + a_{w}) = 114 a_{1} + a_{22} = 38 Now a_{1} + a_{5} + a_{11} + a_{11} = 2(a_{11} + a_{12}) = 2 * 38 = 76',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    12,
    'If α and β are the roots of the equation 375x^2 - 25x - 2 = 0, then lim (n -> ∞) [sum i=0 to n (α^i)] + lim (n -> ∞) [sum i=0 to n (β^i)] is equal to:',
    '2019',
    false,
    '',
    false,
    '21/345',
    '7/116',
    '29/350',
    '1/12',
    false,
    '',
    '',
    '',
    '',
    '4',
    ' 3/5 * x ^ 2 - 25x - 2 = 0 a+| 1 - 25/375 , alpha||= -2 375 lim n -> ∞ sum  (alpha ^ 1 + 1/2 ^ 2) = alpha+ alpha^ 2 + alpha^ 2 +..., alpha n )+( 3 2 +2)^ 2 +..., alpha n  . = a/(1 - a) + beta/(1 - beta) = alpha* beta-2 alpha| beta 1 - (alpha + beta) * alpha*beta 375-375 1 - 25/(37x) - 2/(375 - 25 - 2) * 29/349 = 1/12',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    13,
    'Let f: R -> R be such that for all x ∈ R, (x^2) f(x) and (3x^2 + 3x) are in AP. Then the minimum value of f(x) is:',
    '2020',
    false,
    '',
    false,
    '2',
    '0',
    '3',
    '4',
    false,
    '',
    '',
    '',
    '',
    '2',
    '',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    14,
    'Let a be the first term of a G.P. with positive terms. If the sum of the first n terms is given by Σ_{n=1} to ∞ a * mu^(n+1) = 200, and the sum from m=1 to 100 of a^m = 100, then the sum from n=1 to 2m of a^jn is equal to:',
    '2020',
    false,
    '',
    false,
    '300',
    '150',
    '175',
    '225',
    false,
    '',
    '',
    '',
    '',
    '1',
    ' (11) 200 sum m=1 ^ 100 a jm = (a_{j}*r(t ^ 700 - 1))/(r ^ 2 - 1) - 100 Dividing (1) by () we get t = 2 and adding (1) and () we get A_{2} + a_{3}*a_{4} + a_{5} +...+a 200 +a 321 =300 ar+ar+ a_{250}*r = 300 r( a_{1} + a_{2} +...+a 2 m)=300  + a_{30} = 150 (1) and 100',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    15,
    'If the first term of an AP is 3 and the sum of its first 25 terms is equal to the sum of its next 15 terms, then the common difference of the AP is:',
    '2020',
    false,
    '',
    false,
    '1/6',
    '2 1/4',
    '1/7',
    'None of the above',
    false,
    '',
    '',
    '',
    '',
    '1',
    'Here a = 3S_{25} = S_{n} 2S_{23} = S_{41} 2 * 25/2 * [6 + 24d] = 40/2 * [6 + 39d] 25 6+24d]* 20{6 + 39d} 150 + 600d = 120 + 780d 180d = 30 d = 1/6',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    16,
    'If the sum of the series 20*13 3/5 + 13 9/5 + 13 4/5 up to nth term is 488 and the nth term is negative, then what is the value of the nth term?',
    '2020',
    false,
    '',
    false,
    '41',
    'n = 10',
    'n term is -4 2/5',
    'n term is -4',
    false,
    '',
    '',
    '',
    '',
    '3',
    ' S + = 20 + 19 3/5 + 19 1/5 + 18 4/5 + S_{n} = 488 n 2  40+( n - 9(- 2/5)  =488 n(20 - (n - 1)/5) = 488 n ^ 2 - 101n + 2440 = 0 (n - 40)(n - 61) = 0 For negative term n = 61 thtem = T_{61} = 20 + 60 (- 2/5) = 4',
    false,
    '',
],

[
    'maths',
    'Sequence and Series',
    17,
    'Consider the series t + (t - 2^2 * 1) + (t - 4^2 * 3) + (t - 5^2 * 5) + ... The ordered pair (r, x) is equal to:',
    '2020',
    false,
    '',
    false,
    '(10,103)',
    '(10,97)',
    '(11,103)',
    '(11,103)',
    false,
    '',
    '',
    '',
    '',
    '1',
    ' t + (1 - 2 ^ 2 * 1) + (1 - 4 ^ 2 * 3) + (1 - 5 ^ 2 * 5) +.. (۲۰ 2019) S = 1 + sum i = 1 to 10 [1 - (2r) ^ 2 * (2r - 1)] = 1 + sum r = 1 to i*mathfrak{R} (1 - mathcal{B} * r ^ 3 + 4r ^ 2) =1+10- sum r=1 ^ mathbb R ( partial r^ 2 -4r^ 2 ) = 11 - 8 * ((10 * 11)/2) ^ 2 + 4((10 * 11 * 21)/6) 11 - 2 * (110) ^ 2 + 4 * 55 * 7 11-220 (110-7) 11 - 220 * 103 = alpha-220|| alpha = 11 p = 103 (11,103)',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    18,
    'Let a, b, c, d, and p be any non-zero distinct real numbers such that (a^2 + b^2 + c^2) * p^2 - 2(ab + bc + cd) * p + (k * x^2 + c^2 + d^2) = 0. Then which of the following is true?',
    '2020',
    false,
    '',
    false,
    'a, b, c, d are in G.P.',
    'a, b, c, d are in A.P.',
    'a, c are in G.P.',
    'a, c are in A.P.',
    false,
    '',
    '',
    '',
    '',
    '3',
    ' (ap²-2abp+b²) (bp2bcpc۰ (cp-2cdp+d²) = 0 (ap - b) ^ 2 + (bp - c) ^ 2 + (cp - d) ^ 2 = 0 ap - b = bp - c = cp - d = 0 Rightarrow b/a = c/b = d/c a, b, c, d are in G.P',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    19,
    'The sum of the infinite series 1 + 2/3 + 7/(3^2) + 12/(3^3) + 17/(3^4) + 22/(3^5) + ... is equal to:',
    '2021',
    false,
    '',
    false,
    '9/4',
    '15/4',
    '13/4',
    '1/4',
    false,
    '',
    '',
    '',
    '',
    '3',
    'S= 1 + 2/3 + 7/(3 ^ 2) + 12/(3 ^ 3) + 17/(3 ^ 4) +... 5 3 = 1/3 + 2/(3 ^ 2) + 7/(3 ^ 3) + 12/(3 ^ 4) +... 25 3 = 1 + 1/3 + 5/(3 ^ 2) + 5/(3 ^ 3) + 5/(3 ^ 4) +...+up terms Rightarrow S = 13/4 to infinite',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    20,
    'The sum of the series 7/(3^2 - 1) + 1/(5^2 - 1) + 1/(7^2 - 1) + ... + 1/(20^2 - 1) is equal to:',
    '2021',
    false,
    '',
    false,
    '105/404',
    '25/101',
    '408',
    '99/400',
    false,
    '',
    '',
    '',
    '',
    '1',
    'T_{n} = 1/((2n + 1) ^ 2 - 1) * 1/((2n - 2) * 2n) = 1/(4(n)(n + 1)) = ((n + 1) - n)/(4n(n + 1)) = 1/4 * (1/n - 1/(n + 1)) S = 1/4 * (1 - 1/101) = 1/4 * (100/101) = 25/101',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    21,
    'Let S be the sum of the first 2n terms of an arithmetic progression. Let S_2 be the sum of the first 4n terms. If (S_2 - S_1) = 1000, then the sum of the first n terms of the arithmetic progression is equal to:',
    '2021',
    false,
    '',
    false,
    '1000',
    '7000',
    '35000',
    '3000',
    false,
    '',
    '',
    '',
    '',
    '4',
    'S m = 2 pi 2  2 n+ {2n - 1} (n S2-(4-10) Rightarrow B 2 -s 1 = d Omega 2 [2.a+ 4 eta-9.5]- 2 Omega 2 [2. a + 2eta - 5phi ] 4an= (4n - 1) * 2nf -2n2-(2n-7)dn 2an + nd{8n - 2 - 2n - 1} Rightarrow 2na + 2n|6n - 1| = 1000 2a + (5m - 7) * d = t000 n Now, mathcal S m = 6 pi 2 [2. a + (6n - 7) * d ] = 30r = 1000/n = 3000',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    22,
    'If for x > 0, y = log_10(x) + log_10(x^10) + log_10(x^100), then the ordered pair (x, y) is equal to:',
    '2021',
    false,
    '',
    false,
    '(10, 106)',
    '(106, 10)',
    '(100, 100)',
    '(10^6, 9)',
    false,
    '',
    '',
    '',
    '',
    '1',
    '2+4+6+...2y 3=6+9+...3y = 4/(log_(in)(x)) Rightarrow log 10 x=6 Rightarrow x = 10 ^ 6 Now, y= (log_(ex)(x)) +(log e2 x^ 4 2 )+(log e2 x^ 1 2 )+...,n) y=( 1 + 1/3 + 1/9 +...x)log - pi x y = (1/(1 - 1/3)) * log_12(x) = 9 50, (x, y) = (10 deg, 9)',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    23,
    'Let a, b, c, ... be in an arithmetic progression such that the sum of the arithmetic progression is 189. If the sum from n = 1 to 30 is equal to 4, then the value of the sum is:',
    '2021',
    false,
    '',
    false,
    '57',
    '72',
    '48',
    '36',
    false,
    '',
    '',
    '',
    '',
    '1',
    'um n=1 ^ 20 1 a n overline a n + 1 = sum n=1 ^ 20 1 B n ( overline B n + overline O ) = 1/phi * sum n = 1 to ∞ (1/a_{n} - 1/(a_{n} + phi)) Rightarrow 1/d * (1/a_{1} - 1/a_{2r}) = 4 9 (Given) Rightarrow 1/d * ((a_{21} - a_{1})/(a_{1}*a_{21})) = 4/9 Rightarrow 1/d * ((a_{1} + 20d - a_{1})/(a_{1}*a_{2})) = 4 9 Rightarrow a,a 2 =45 (1) Now sum of first 21 terms 21/2 * (2n_{1} + 20phi) = 185 Rightarrow a_{1} + 10d = 9 (2) For equation (1) & (2) we get a_{1} = 3delta*d = 3/5 OR a 1 =15. Delta*d = - 3/5 So, a_{0}*a_{10} = (a_{1} + 5d)(a_{1} + 15d) a +a mapsto s =72 Option (2)',
    false,
    '',
],


[
    'maths',
    'Sequence and Series',
    24,
    'Let the six numbers a, a + d, a + 2d, a + 3d, a + 4d, a + 5d be in an arithmetic progression. If a_1 + a_3 = 10 and the mean of these numbers is 5, then the variance is σ². What is the value of Be³?',
    '2023',
    false,
    '',
    false,
    '220',
    '210',
    '200',
    '105',
    false,
    '',
    '',
    '',
    '',
    '4',
    'a_{1} + a_{3} = 10 =a 1 +d Rightarrow5 a_{1} + a_{2} + a_{3} + a_{6} + a_{5} = 57 Rightarrow 6/2 * {a, az} = 57 Rightarrow a_{1} + a_{1} = 19 Rightarrow 2ar + 5d = 19and*a_{1} + d = 5 Rightarrow a_{1} = 2 , d = 3 Numbers 2, 5, 8, 11, 14, 17 Variance mean of squares-square of mean (2 ^ 2 + 5 ^ 2 + 8 ^ 2 + (11) ^ 2 + (14) ^ 2 + (17) ^ 2)/6 - (19/2) ^ 2 = 699/6 - 361/4 = 105/4 8sigma ^ 2 = 210',
    false,
    '',
],

[
    'maths',
    'Sequence and Series',
    25,
    'If m arithmetic means (A.Ms) and three geometric means (G.Ms) are inserted between 3 and 243 such that the 4th A.M. is equal to 2 G.M., then m is equal to:',
    '2020',
    false,
    '',
    false,
    '8',
    '9',
    '10',
    '11',
    false,
    '',
    '',
    '',
    '',
    '2',
    '3, A_{1} ,A 2 ...A m ,243 Is * 243 = 3 + (m + 1) * d d = 240/(m + 1) Also 3, G_{5} , 243 G_{2} G_{2} ^ 2 = 243 * 3 G_{2} = sqrt(243 * 3) = 27 Now, A * = 3 + 4d = 3 + 960/(m + 1) A_{4} = G_{2} 27 = 3 + 960/(m + 1)',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    26,
    'For k ∈ N, let α > 0. Then the value of 1/(α(α+1)(α+2)...(α+20)) = sum k=0 to 2Q A_n/(α + k), 100 * ((A_14 + A_16)/A_13)^2 is:',
    '2021',
    false,
    '',
    false,
    '100',
    '200',
    '300',
    '400',
    false,
    '',
    '',
    '',
    '',
    '1',
    '9/(alpha(alpha + Omega)(alpha + 2)(alpha + 20)) = sum k = 0 to ∞ A_{k}/(alpha + k) A_{14} = 4/((- 14)(- 13)) * 1/((- 7)(7) - (6)) = 4 14 backslash6A tA = 1 (-15)(-14)...(-1)(1)...(5) = 1 15+51 A 73 = 1 (-13)...(-7)( eta)...(7) = - 7/(13!0.71) A e4 A e3 = 1 14!(61 *-13(e7)= - 7/14 = - 1/2 A_{11}/A_{13} = 1/151.51 * (- 131) * 71 = 42/(15 * 14) = 1/5',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    27,
    'Let a_n be an A.P. with common difference -3 and b_n be a G.P. with common ratio 2. If c_2 = 12, then sum k=1 to 18 C_k C_3 = 13. Find the value of C_k:',
    '2021',
    false,
    '',
    false,
    '36',
    '48',
    '56',
    '72',
    false,
    '',
    '',
    '',
    '',
    '3',
    '( A 14 A t3 + A 13 A 13 )^ 2 = 100 * (- 1/2 + 1/5) ^ 2 = 9 27. c_{2} = a_{2} + b_{2} = a_{1} - 3 + 2b_{1} = 12 a_{1} + 2b_{1} = 15 c_{3} = a_{3} + b_{3} = a_{1} - 6 + 4b_{1} = 13 a_{1} + 4b_{2} = 19 (2) from (1) & (2) b = a_{1} = 11 sum k = 1 to 12 C k = sum k=1 ^ 12 ( partial k +b k )= sum k=1 ^ 12 partial k + sum k=1 ^ 12 b k = 10/2 * (2 * 11 * 9(- 3)) * (2(2 ^ 16 - 1))/(2 - 1) = 5(22 - 27) + 2(1023) -2046-25-2021 (1)',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    28,
    'Let A = sum l=1 to 10 sum l=1 to 10 t(1) and B = sum from 1 to 10. Then A + B is equal to:',
    '2022',
    false,
    '',
    false,
    '100',
    '200',
    '300',
    '400',
    false,
    '',
    '',
    '',
    '',
    '2',
    'A_{i} = sum i = 1 to k_{2} sum i = 1 to 16 min * {i, j} B = sum i = 1 to m sum i = 1 to m max * {i, 1} A-min (1) - min (1,2)+ min (1,10) (1) 1times Bmax (1) max (1.2) max (1,10) (10-10-10) (9+9+9) 17 spes (1) 1times A + B = 20(1 + 2 + 3 + 10) = 20 * (10 * 11)/2 = 10 * 110 =1 100',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    29,
    'If the sum of the first ten terms of the series 1/5 + 2/65 + 3/325 + 4/1025 + 5/2501 +... is m and n is the sum of these terms, then m + n is equal to:',
    '2022',
    false,
    '',
    false,
    '105',
    '115',
    '125',
    '130',
    false,
    '',
    '',
    '',
    '',
    '1',
    '1/5 + 2/65 + 3/325 + 4/1025 + 5/2501 + T_{n} = n/(4n ^ 4 + 1) = n/((2n ^ 2 + 1) ^ 2 - (2n) ^ 2) = n/((2n ^ 2 + 2n + 1) - (2n ^ 2 - 2n + 7)) = 1/4 * [1/(2n ^ 2 - 2n + 1) - 1/(2n ^ 2 + 2n + 1)] mathcal S 10 = sum n - 1 to 12 T n = 1 4 [ 1/1 - 1/5 + 1/5 - 1/13 +... 1 200+20+1 ] = 1/4 * [1 - 1/221] = 1/4 * 220/221 = 55/221 * m/n m + n = 55 + 221 = 276',
    false,
    '',
],
[
    'maths',
    'Sequence and Series',
    30,
    'If the sum of the series 1 + 2 + 3 + ... upto n terms and 13 + 25 + 37 + 49 + ... upto n terms is 5, then the value of n is:',
    '2023',
    false,
    '',
    false,
    '10',
    '20',
    '30',
    '40',
    false,
    '',
    '',
    '',
    '',
    '4',
    '1^ 2 +2^ 3 +3^ 3 ...+ n ^ 3 * ((n(n + 1))/2) ^ 2 13+2 5+37+ sum r = 1 to n r * (2r + 9) = sum r = 1 to n (2r ^ 2 + r) = (2n(n + 1)(2n + 1))/6 + (n(n + 1) * 2)/2 = (n(n + 1))/6 * (2(2n + 1) + 3) = (n(n + 1))/2 * (4n + 5)/3 = (n ^ 2 * (n + 1) ^ 2)/((n(n + 1))/2 * (4n + 5)/3) = 9/5 Rightarrow (5n(n + 1))/2 = (9(4n + 5))/3 > 15n(n + 1) = 18(4n + 5) Rightarrow 15n ^ 2 + 15n = 72n + 90 Rightarrow15n^ 2 -57n-90 Rightarrow 5n ^ 2 - 19n - 30 = Rightarrow (n - 5)(5n + 6) = 0 Rightarrow n = - 6/5 * or * 5 7n = 5 n terms',
    false,
    '',
],


];