List<String> bookInfo = [
  '''"Think and Grow Rich," published in 1937 by Napoleon Hill, offers 13 principles for success, such as desire and faith. With over 70 million copies sold, it's a must-read for anyone seeking financial independence and personal growth. Ready to transform your life?''',
  '''The Psychology of Money” by Morgan Housel explores the intricate interplay between psychology and finance, offering insights into the hidden motivations and behaviors that shape our financial decisions. This book is essential reading for anyone seeking a deeper understanding of the human side of wealth.''',
  '''Mindset explains the difference between having a fixed and a growth mindset, why one trumps the other, and what you can do to adopt the right one.''',
  '''Atomic Habits by James Clear is a groundbreaking self-improvement guide, revealing the transformative power of small habits for lasting personal development. Through scientific insights and practical strategies, Clear offers a roadmap to harness the cumulative impact of tiny changes, leading to remarkable results in all aspects of life.''',
  '''"Think and Grow Rich," published in 1937 by Napoleon Hill, offers 13 principles for success, such as desire and faith. With over 70 million copies sold, it's a must-read for anyone seeking financial independence and personal growth. Ready to transform your life?''',
  '''The Psychology of Money” by Morgan Housel explores the intricate interplay between psychology and finance, offering insights into the hidden motivations and behaviors that shape our financial decisions. This book is essential reading for anyone seeking a deeper understanding of the human side of wealth.''',
  '''Mindset explains the difference between having a fixed and a growth mindset, why one trumps the other, and what you can do to adopt the right one.''',
  '''Atomic Habits by James Clear is a groundbreaking self-improvement guide, revealing the transformative power of small habits for lasting personal development. Through scientific insights and practical strategies, Clear offers a roadmap to harness the cumulative impact of tiny changes, leading to remarkable results in all aspects of life.''',
];
